import MnemonicX86 from '../../x86/MnemonicX86';
import MnemonicVariationsX86 from '../../x86/MnemonicVariationsX86';
import * as a from '../atoms';

const mnemonic_add_0 = new MnemonicX86;
mnemonic_add_0.mnemonic                = "mov";
mnemonic_add_0.operandSize             = 8;
mnemonic_add_0.opcode                  = 136;
mnemonic_add_0.operandTemplates        = [[a.r, a.m], [a.r]];
mnemonic_add_0.opreg                   = -1;
mnemonic_add_0.operandSizeDefault      = 32;
mnemonic_add_0.lock                    = false;
mnemonic_add_0.regInOp                 = false;
mnemonic_add_0.opcodeDirectionBit      = true;
mnemonic_add_0.useModrm                = true;
mnemonic_add_0.rep                     = false;
mnemonic_add_0.repne                   = false;
mnemonic_add_0.prefixes                = null;
mnemonic_add_0.opEncoding              = "mr";
mnemonic_add_0.rex                     = null;
mnemonic_add_0.vex                     = null;
mnemonic_add_0.evex                    = null;
mnemonic_add_0.mode                    = 63;
mnemonic_add_0.extensions              = null;

const mnemonic_add_1 = new MnemonicX86;
mnemonic_add_1.mnemonic                = "mov";
mnemonic_add_1.operandSize             = 8;
mnemonic_add_1.opcode                  = 138;
mnemonic_add_1.operandTemplates        = [[a.r], [a.r, a.m]];
mnemonic_add_1.opreg                   = -1;
mnemonic_add_1.operandSizeDefault      = 32;
mnemonic_add_1.lock                    = false;
mnemonic_add_1.regInOp                 = false;
mnemonic_add_1.opcodeDirectionBit      = true;
mnemonic_add_1.useModrm                = true;
mnemonic_add_1.rep                     = false;
mnemonic_add_1.repne                   = false;
mnemonic_add_1.prefixes                = null;
mnemonic_add_1.opEncoding              = "rm";
mnemonic_add_1.rex                     = null;
mnemonic_add_1.vex                     = null;
mnemonic_add_1.evex                    = null;
mnemonic_add_1.mode                    = 63;
mnemonic_add_1.extensions              = null;

const mnemonic_add_2 = new MnemonicX86;
mnemonic_add_2.mnemonic                = "mov";
mnemonic_add_2.operandSize             = 16;
mnemonic_add_2.opcode                  = 137;
mnemonic_add_2.operandTemplates        = [[a.r, a.m], [a.r]];
mnemonic_add_2.opreg                   = -1;
mnemonic_add_2.operandSizeDefault      = 32;
mnemonic_add_2.lock                    = false;
mnemonic_add_2.regInOp                 = false;
mnemonic_add_2.opcodeDirectionBit      = true;
mnemonic_add_2.useModrm                = true;
mnemonic_add_2.rep                     = false;
mnemonic_add_2.repne                   = false;
mnemonic_add_2.prefixes                = null;
mnemonic_add_2.opEncoding              = "mr";
mnemonic_add_2.rex                     = null;
mnemonic_add_2.vex                     = null;
mnemonic_add_2.evex                    = null;
mnemonic_add_2.mode                    = 63;
mnemonic_add_2.extensions              = null;

const mnemonic_add_3 = new MnemonicX86;
mnemonic_add_3.mnemonic                = "mov";
mnemonic_add_3.operandSize             = 16;
mnemonic_add_3.opcode                  = 139;
mnemonic_add_3.operandTemplates        = [[a.r], [a.r, a.m]];
mnemonic_add_3.opreg                   = -1;
mnemonic_add_3.operandSizeDefault      = 32;
mnemonic_add_3.lock                    = false;
mnemonic_add_3.regInOp                 = false;
mnemonic_add_3.opcodeDirectionBit      = true;
mnemonic_add_3.useModrm                = true;
mnemonic_add_3.rep                     = false;
mnemonic_add_3.repne                   = false;
mnemonic_add_3.prefixes                = null;
mnemonic_add_3.opEncoding              = "rm";
mnemonic_add_3.rex                     = null;
mnemonic_add_3.vex                     = null;
mnemonic_add_3.evex                    = null;
mnemonic_add_3.mode                    = 63;
mnemonic_add_3.extensions              = null;

const mnemonic_add_4 = new MnemonicX86;
mnemonic_add_4.mnemonic                = "mov";
mnemonic_add_4.operandSize             = 32;
mnemonic_add_4.opcode                  = 137;
mnemonic_add_4.operandTemplates        = [[a.r, a.m], [a.r]];
mnemonic_add_4.opreg                   = -1;
mnemonic_add_4.operandSizeDefault      = 32;
mnemonic_add_4.lock                    = false;
mnemonic_add_4.regInOp                 = false;
mnemonic_add_4.opcodeDirectionBit      = true;
mnemonic_add_4.useModrm                = true;
mnemonic_add_4.rep                     = false;
mnemonic_add_4.repne                   = false;
mnemonic_add_4.prefixes                = null;
mnemonic_add_4.opEncoding              = "mr";
mnemonic_add_4.rex                     = null;
mnemonic_add_4.vex                     = null;
mnemonic_add_4.evex                    = null;
mnemonic_add_4.mode                    = 63;
mnemonic_add_4.extensions              = null;

const mnemonic_add_5 = new MnemonicX86;
mnemonic_add_5.mnemonic                = "mov";
mnemonic_add_5.operandSize             = 32;
mnemonic_add_5.opcode                  = 139;
mnemonic_add_5.operandTemplates        = [[a.r], [a.r, a.m]];
mnemonic_add_5.opreg                   = -1;
mnemonic_add_5.operandSizeDefault      = 32;
mnemonic_add_5.lock                    = false;
mnemonic_add_5.regInOp                 = false;
mnemonic_add_5.opcodeDirectionBit      = true;
mnemonic_add_5.useModrm                = true;
mnemonic_add_5.rep                     = false;
mnemonic_add_5.repne                   = false;
mnemonic_add_5.prefixes                = null;
mnemonic_add_5.opEncoding              = "rm";
mnemonic_add_5.rex                     = null;
mnemonic_add_5.vex                     = null;
mnemonic_add_5.evex                    = null;
mnemonic_add_5.mode                    = 63;
mnemonic_add_5.extensions              = null;

const mnemonic_add_6 = new MnemonicX86;
mnemonic_add_6.mnemonic                = "mov";
mnemonic_add_6.operandSize             = 64;
mnemonic_add_6.opcode                  = 137;
mnemonic_add_6.operandTemplates        = [[a.r, a.m], [a.r]];
mnemonic_add_6.opreg                   = -1;
mnemonic_add_6.operandSizeDefault      = 32;
mnemonic_add_6.lock                    = false;
mnemonic_add_6.regInOp                 = false;
mnemonic_add_6.opcodeDirectionBit      = true;
mnemonic_add_6.useModrm                = true;
mnemonic_add_6.rep                     = false;
mnemonic_add_6.repne                   = false;
mnemonic_add_6.prefixes                = null;
mnemonic_add_6.opEncoding              = "mr";
mnemonic_add_6.rex                     = null;
mnemonic_add_6.vex                     = null;
mnemonic_add_6.evex                    = null;
mnemonic_add_6.mode                    = 63;
mnemonic_add_6.extensions              = null;

const mnemonic_add_7 = new MnemonicX86;
mnemonic_add_7.mnemonic                = "mov";
mnemonic_add_7.operandSize             = 64;
mnemonic_add_7.opcode                  = 139;
mnemonic_add_7.operandTemplates        = [[a.r], [a.r, a.m]];
mnemonic_add_7.opreg                   = -1;
mnemonic_add_7.operandSizeDefault      = 32;
mnemonic_add_7.lock                    = false;
mnemonic_add_7.regInOp                 = false;
mnemonic_add_7.opcodeDirectionBit      = true;
mnemonic_add_7.useModrm                = true;
mnemonic_add_7.rep                     = false;
mnemonic_add_7.repne                   = false;
mnemonic_add_7.prefixes                = null;
mnemonic_add_7.opEncoding              = "rm";
mnemonic_add_7.rex                     = null;
mnemonic_add_7.vex                     = null;
mnemonic_add_7.evex                    = null;
mnemonic_add_7.mode                    = 63;
mnemonic_add_7.extensions              = null;

const mnemonic_add_8 = new MnemonicX86;
mnemonic_add_8.mnemonic                = "mov";
mnemonic_add_8.operandSize             = 16;
mnemonic_add_8.opcode                  = 140;
mnemonic_add_8.operandTemplates        = [[a.r, a.m], [a.r]];
mnemonic_add_8.opreg                   = -1;
mnemonic_add_8.operandSizeDefault      = 32;
mnemonic_add_8.lock                    = false;
mnemonic_add_8.regInOp                 = false;
mnemonic_add_8.opcodeDirectionBit      = false;
mnemonic_add_8.useModrm                = true;
mnemonic_add_8.rep                     = false;
mnemonic_add_8.repne                   = false;
mnemonic_add_8.prefixes                = null;
mnemonic_add_8.opEncoding              = "rm";
mnemonic_add_8.rex                     = null;
mnemonic_add_8.vex                     = null;
mnemonic_add_8.evex                    = null;
mnemonic_add_8.mode                    = 63;
mnemonic_add_8.extensions              = null;

const mnemonic_add_9 = new MnemonicX86;
mnemonic_add_9.mnemonic                = "mov";
mnemonic_add_9.operandSize             = 16;
mnemonic_add_9.opcode                  = 142;
mnemonic_add_9.operandTemplates        = [[a.r], [a.r, a.m]];
mnemonic_add_9.opreg                   = -1;
mnemonic_add_9.operandSizeDefault      = 32;
mnemonic_add_9.lock                    = false;
mnemonic_add_9.regInOp                 = false;
mnemonic_add_9.opcodeDirectionBit      = false;
mnemonic_add_9.useModrm                = true;
mnemonic_add_9.rep                     = false;
mnemonic_add_9.repne                   = false;
mnemonic_add_9.prefixes                = null;
mnemonic_add_9.opEncoding              = "rm";
mnemonic_add_9.rex                     = null;
mnemonic_add_9.vex                     = null;
mnemonic_add_9.evex                    = null;
mnemonic_add_9.mode                    = 63;
mnemonic_add_9.extensions              = null;

const mnemonic_add_10 = new MnemonicX86;
mnemonic_add_10.mnemonic                = "mov";
mnemonic_add_10.operandSize             = 16;
mnemonic_add_10.opcode                  = 140;
mnemonic_add_10.operandTemplates        = [[a.r, a.m], [a.r]];
mnemonic_add_10.opreg                   = -1;
mnemonic_add_10.operandSizeDefault      = 32;
mnemonic_add_10.lock                    = false;
mnemonic_add_10.regInOp                 = false;
mnemonic_add_10.opcodeDirectionBit      = false;
mnemonic_add_10.useModrm                = true;
mnemonic_add_10.rep                     = false;
mnemonic_add_10.repne                   = false;
mnemonic_add_10.prefixes                = null;
mnemonic_add_10.opEncoding              = "rm";
mnemonic_add_10.rex                     = null;
mnemonic_add_10.vex                     = null;
mnemonic_add_10.evex                    = null;
mnemonic_add_10.mode                    = 63;
mnemonic_add_10.extensions              = null;

const mnemonic_add_11 = new MnemonicX86;
mnemonic_add_11.mnemonic                = "mov";
mnemonic_add_11.operandSize             = 16;
mnemonic_add_11.opcode                  = 142;
mnemonic_add_11.operandTemplates        = [[a.r], [a.r, a.m]];
mnemonic_add_11.opreg                   = -1;
mnemonic_add_11.operandSizeDefault      = 32;
mnemonic_add_11.lock                    = false;
mnemonic_add_11.regInOp                 = false;
mnemonic_add_11.opcodeDirectionBit      = false;
mnemonic_add_11.useModrm                = true;
mnemonic_add_11.rep                     = false;
mnemonic_add_11.repne                   = false;
mnemonic_add_11.prefixes                = null;
mnemonic_add_11.opEncoding              = "rm";
mnemonic_add_11.rex                     = null;
mnemonic_add_11.vex                     = null;
mnemonic_add_11.evex                    = null;
mnemonic_add_11.mode                    = 63;
mnemonic_add_11.extensions              = null;

const mnemonic_add_12 = new MnemonicX86;
mnemonic_add_12.mnemonic                = "mov";
mnemonic_add_12.operandSize             = 8;
mnemonic_add_12.opcode                  = 176;
mnemonic_add_12.operandTemplates        = [[a.r], [a.imm8]];
mnemonic_add_12.opreg                   = -1;
mnemonic_add_12.operandSizeDefault      = 32;
mnemonic_add_12.lock                    = false;
mnemonic_add_12.regInOp                 = true;
mnemonic_add_12.opcodeDirectionBit      = false;
mnemonic_add_12.useModrm                = true;
mnemonic_add_12.rep                     = false;
mnemonic_add_12.repne                   = false;
mnemonic_add_12.prefixes                = null;
mnemonic_add_12.opEncoding              = "rm";
mnemonic_add_12.rex                     = null;
mnemonic_add_12.vex                     = null;
mnemonic_add_12.evex                    = null;
mnemonic_add_12.mode                    = 63;
mnemonic_add_12.extensions              = null;

const mnemonic_add_13 = new MnemonicX86;
mnemonic_add_13.mnemonic                = "mov";
mnemonic_add_13.operandSize             = 16;
mnemonic_add_13.opcode                  = 184;
mnemonic_add_13.operandTemplates        = [[a.r], [a.imm16]];
mnemonic_add_13.opreg                   = -1;
mnemonic_add_13.operandSizeDefault      = 32;
mnemonic_add_13.lock                    = false;
mnemonic_add_13.regInOp                 = true;
mnemonic_add_13.opcodeDirectionBit      = false;
mnemonic_add_13.useModrm                = true;
mnemonic_add_13.rep                     = false;
mnemonic_add_13.repne                   = false;
mnemonic_add_13.prefixes                = null;
mnemonic_add_13.opEncoding              = "rm";
mnemonic_add_13.rex                     = null;
mnemonic_add_13.vex                     = null;
mnemonic_add_13.evex                    = null;
mnemonic_add_13.mode                    = 63;
mnemonic_add_13.extensions              = null;

const mnemonic_add_14 = new MnemonicX86;
mnemonic_add_14.mnemonic                = "mov";
mnemonic_add_14.operandSize             = 32;
mnemonic_add_14.opcode                  = 184;
mnemonic_add_14.operandTemplates        = [[a.r], [a.imm32]];
mnemonic_add_14.opreg                   = -1;
mnemonic_add_14.operandSizeDefault      = 32;
mnemonic_add_14.lock                    = false;
mnemonic_add_14.regInOp                 = true;
mnemonic_add_14.opcodeDirectionBit      = false;
mnemonic_add_14.useModrm                = true;
mnemonic_add_14.rep                     = false;
mnemonic_add_14.repne                   = false;
mnemonic_add_14.prefixes                = null;
mnemonic_add_14.opEncoding              = "rm";
mnemonic_add_14.rex                     = null;
mnemonic_add_14.vex                     = null;
mnemonic_add_14.evex                    = null;
mnemonic_add_14.mode                    = 63;
mnemonic_add_14.extensions              = null;

const mnemonic_add_15 = new MnemonicX86;
mnemonic_add_15.mnemonic                = "mov";
mnemonic_add_15.operandSize             = 64;
mnemonic_add_15.opcode                  = 184;
mnemonic_add_15.operandTemplates        = [[a.r], [a.imm64]];
mnemonic_add_15.opreg                   = -1;
mnemonic_add_15.operandSizeDefault      = 32;
mnemonic_add_15.lock                    = false;
mnemonic_add_15.regInOp                 = true;
mnemonic_add_15.opcodeDirectionBit      = false;
mnemonic_add_15.useModrm                = true;
mnemonic_add_15.rep                     = false;
mnemonic_add_15.repne                   = false;
mnemonic_add_15.prefixes                = null;
mnemonic_add_15.opEncoding              = "rm";
mnemonic_add_15.rex                     = null;
mnemonic_add_15.vex                     = null;
mnemonic_add_15.evex                    = null;
mnemonic_add_15.mode                    = 63;
mnemonic_add_15.extensions              = null;

const mnemonic_add_16 = new MnemonicX86;
mnemonic_add_16.mnemonic                = "mov";
mnemonic_add_16.operandSize             = 8;
mnemonic_add_16.opcode                  = 198;
mnemonic_add_16.operandTemplates        = [[a.r, a.m], [a.imm8]];
mnemonic_add_16.opreg                   = 0;
mnemonic_add_16.operandSizeDefault      = 32;
mnemonic_add_16.lock                    = false;
mnemonic_add_16.regInOp                 = false;
mnemonic_add_16.opcodeDirectionBit      = false;
mnemonic_add_16.useModrm                = true;
mnemonic_add_16.rep                     = false;
mnemonic_add_16.repne                   = false;
mnemonic_add_16.prefixes                = null;
mnemonic_add_16.opEncoding              = "rm";
mnemonic_add_16.rex                     = null;
mnemonic_add_16.vex                     = null;
mnemonic_add_16.evex                    = null;
mnemonic_add_16.mode                    = 63;
mnemonic_add_16.extensions              = null;

const mnemonic_add_17 = new MnemonicX86;
mnemonic_add_17.mnemonic                = "mov";
mnemonic_add_17.operandSize             = 16;
mnemonic_add_17.opcode                  = 199;
mnemonic_add_17.operandTemplates        = [[a.r, a.m], [a.imm16]];
mnemonic_add_17.opreg                   = 0;
mnemonic_add_17.operandSizeDefault      = 32;
mnemonic_add_17.lock                    = false;
mnemonic_add_17.regInOp                 = false;
mnemonic_add_17.opcodeDirectionBit      = false;
mnemonic_add_17.useModrm                = true;
mnemonic_add_17.rep                     = false;
mnemonic_add_17.repne                   = false;
mnemonic_add_17.prefixes                = null;
mnemonic_add_17.opEncoding              = "rm";
mnemonic_add_17.rex                     = null;
mnemonic_add_17.vex                     = null;
mnemonic_add_17.evex                    = null;
mnemonic_add_17.mode                    = 63;
mnemonic_add_17.extensions              = null;

const mnemonic_add_18 = new MnemonicX86;
mnemonic_add_18.mnemonic                = "mov";
mnemonic_add_18.operandSize             = 32;
mnemonic_add_18.opcode                  = 199;
mnemonic_add_18.operandTemplates        = [[a.r, a.m], [a.imm32]];
mnemonic_add_18.opreg                   = 0;
mnemonic_add_18.operandSizeDefault      = 32;
mnemonic_add_18.lock                    = false;
mnemonic_add_18.regInOp                 = false;
mnemonic_add_18.opcodeDirectionBit      = false;
mnemonic_add_18.useModrm                = true;
mnemonic_add_18.rep                     = false;
mnemonic_add_18.repne                   = false;
mnemonic_add_18.prefixes                = null;
mnemonic_add_18.opEncoding              = "rm";
mnemonic_add_18.rex                     = null;
mnemonic_add_18.vex                     = null;
mnemonic_add_18.evex                    = null;
mnemonic_add_18.mode                    = 63;
mnemonic_add_18.extensions              = null;

const mnemonic_add_19 = new MnemonicX86;
mnemonic_add_19.mnemonic                = "mov";
mnemonic_add_19.operandSize             = 64;
mnemonic_add_19.opcode                  = 199;
mnemonic_add_19.operandTemplates        = [[a.r, a.m], [a.imm32]];
mnemonic_add_19.opreg                   = 0;
mnemonic_add_19.operandSizeDefault      = 32;
mnemonic_add_19.lock                    = false;
mnemonic_add_19.regInOp                 = false;
mnemonic_add_19.opcodeDirectionBit      = false;
mnemonic_add_19.useModrm                = true;
mnemonic_add_19.rep                     = false;
mnemonic_add_19.repne                   = false;
mnemonic_add_19.prefixes                = null;
mnemonic_add_19.opEncoding              = "rm";
mnemonic_add_19.rex                     = null;
mnemonic_add_19.vex                     = null;
mnemonic_add_19.evex                    = null;
mnemonic_add_19.mode                    = 63;
mnemonic_add_19.extensions              = null;

const mnemonic_add_20 = new MnemonicX86;
mnemonic_add_20.mnemonic                = "mov";
mnemonic_add_20.operandSize             = 32;
mnemonic_add_20.opcode                  = 3872;
mnemonic_add_20.operandTemplates        = [[a.r], [a.cr0, a.cr1, a.cr2, a.cr3, a.cr4, a.cr5, a.cr6, a.cr7]];
mnemonic_add_20.opreg                   = -1;
mnemonic_add_20.operandSizeDefault      = 32;
mnemonic_add_20.lock                    = false;
mnemonic_add_20.regInOp                 = false;
mnemonic_add_20.opcodeDirectionBit      = true;
mnemonic_add_20.useModrm                = true;
mnemonic_add_20.rep                     = false;
mnemonic_add_20.repne                   = false;
mnemonic_add_20.prefixes                = null;
mnemonic_add_20.opEncoding              = "rm";
mnemonic_add_20.rex                     = null;
mnemonic_add_20.vex                     = null;
mnemonic_add_20.evex                    = null;
mnemonic_add_20.mode                    = 12;
mnemonic_add_20.extensions              = null;

const mnemonic_add_21 = new MnemonicX86;
mnemonic_add_21.mnemonic                = "mov";
mnemonic_add_21.operandSize             = 64;
mnemonic_add_21.opcode                  = 3872;
mnemonic_add_21.operandTemplates        = [[a.r], [a.cr0, a.cr1, a.cr2, a.cr3, a.cr4, a.cr5, a.cr6, a.cr7]];
mnemonic_add_21.opreg                   = -1;
mnemonic_add_21.operandSizeDefault      = 32;
mnemonic_add_21.lock                    = false;
mnemonic_add_21.regInOp                 = false;
mnemonic_add_21.opcodeDirectionBit      = true;
mnemonic_add_21.useModrm                = true;
mnemonic_add_21.rep                     = false;
mnemonic_add_21.repne                   = false;
mnemonic_add_21.prefixes                = null;
mnemonic_add_21.opEncoding              = "rm";
mnemonic_add_21.rex                     = null;
mnemonic_add_21.vex                     = null;
mnemonic_add_21.evex                    = null;
mnemonic_add_21.mode                    = 32;
mnemonic_add_21.extensions              = null;

const mnemonic_add_22 = new MnemonicX86;
mnemonic_add_22.mnemonic                = "mov";
mnemonic_add_22.operandSize             = 64;
mnemonic_add_22.opcode                  = 3872;
mnemonic_add_22.operandTemplates        = [[a.r], [a.cr8]];
mnemonic_add_22.opreg                   = 0;
mnemonic_add_22.operandSizeDefault      = 32;
mnemonic_add_22.lock                    = false;
mnemonic_add_22.regInOp                 = false;
mnemonic_add_22.opcodeDirectionBit      = false;
mnemonic_add_22.useModrm                = true;
mnemonic_add_22.rep                     = false;
mnemonic_add_22.repne                   = false;
mnemonic_add_22.prefixes                = null;
mnemonic_add_22.opEncoding              = "rm";
mnemonic_add_22.rex                     = null;
mnemonic_add_22.vex                     = null;
mnemonic_add_22.evex                    = null;
mnemonic_add_22.mode                    = 32;
mnemonic_add_22.extensions              = null;

const mnemonic_add_23 = new MnemonicX86;
mnemonic_add_23.mnemonic                = "mov";
mnemonic_add_23.operandSize             = 32;
mnemonic_add_23.opcode                  = 3874;
mnemonic_add_23.operandTemplates        = [[a.cr0, a.cr1, a.cr2, a.cr3, a.cr4, a.cr5, a.cr6, a.cr7], [a.r]];
mnemonic_add_23.opreg                   = -1;
mnemonic_add_23.operandSizeDefault      = 32;
mnemonic_add_23.lock                    = false;
mnemonic_add_23.regInOp                 = false;
mnemonic_add_23.opcodeDirectionBit      = true;
mnemonic_add_23.useModrm                = true;
mnemonic_add_23.rep                     = false;
mnemonic_add_23.repne                   = false;
mnemonic_add_23.prefixes                = null;
mnemonic_add_23.opEncoding              = "rm";
mnemonic_add_23.rex                     = null;
mnemonic_add_23.vex                     = null;
mnemonic_add_23.evex                    = null;
mnemonic_add_23.mode                    = 12;
mnemonic_add_23.extensions              = null;

const mnemonic_add_24 = new MnemonicX86;
mnemonic_add_24.mnemonic                = "mov";
mnemonic_add_24.operandSize             = 64;
mnemonic_add_24.opcode                  = 3874;
mnemonic_add_24.operandTemplates        = [[a.cr0, a.cr1, a.cr2, a.cr3, a.cr4, a.cr5, a.cr6, a.cr7], [a.r]];
mnemonic_add_24.opreg                   = -1;
mnemonic_add_24.operandSizeDefault      = 32;
mnemonic_add_24.lock                    = false;
mnemonic_add_24.regInOp                 = false;
mnemonic_add_24.opcodeDirectionBit      = true;
mnemonic_add_24.useModrm                = true;
mnemonic_add_24.rep                     = false;
mnemonic_add_24.repne                   = false;
mnemonic_add_24.prefixes                = null;
mnemonic_add_24.opEncoding              = "rm";
mnemonic_add_24.rex                     = null;
mnemonic_add_24.vex                     = null;
mnemonic_add_24.evex                    = null;
mnemonic_add_24.mode                    = 32;
mnemonic_add_24.extensions              = null;

const mnemonic_add_25 = new MnemonicX86;
mnemonic_add_25.mnemonic                = "mov";
mnemonic_add_25.operandSize             = 64;
mnemonic_add_25.opcode                  = 3874;
mnemonic_add_25.operandTemplates        = [[a.cr8], [a.r]];
mnemonic_add_25.opreg                   = 0;
mnemonic_add_25.operandSizeDefault      = 32;
mnemonic_add_25.lock                    = false;
mnemonic_add_25.regInOp                 = false;
mnemonic_add_25.opcodeDirectionBit      = false;
mnemonic_add_25.useModrm                = true;
mnemonic_add_25.rep                     = false;
mnemonic_add_25.repne                   = false;
mnemonic_add_25.prefixes                = null;
mnemonic_add_25.opEncoding              = "rm";
mnemonic_add_25.rex                     = null;
mnemonic_add_25.vex                     = null;
mnemonic_add_25.evex                    = null;
mnemonic_add_25.mode                    = 32;
mnemonic_add_25.extensions              = null;

const mnemonic_add_26 = new MnemonicX86;
mnemonic_add_26.mnemonic                = "mov";
mnemonic_add_26.operandSize             = 32;
mnemonic_add_26.opcode                  = 3873;
mnemonic_add_26.operandTemplates        = [[a.r], [a.dr0, a.dr1, a.dr2, a.dr3, a.dr4, a.dr5, a.dr6, a.dr7]];
mnemonic_add_26.opreg                   = -1;
mnemonic_add_26.operandSizeDefault      = 32;
mnemonic_add_26.lock                    = false;
mnemonic_add_26.regInOp                 = false;
mnemonic_add_26.opcodeDirectionBit      = true;
mnemonic_add_26.useModrm                = true;
mnemonic_add_26.rep                     = false;
mnemonic_add_26.repne                   = false;
mnemonic_add_26.prefixes                = null;
mnemonic_add_26.opEncoding              = "rm";
mnemonic_add_26.rex                     = null;
mnemonic_add_26.vex                     = null;
mnemonic_add_26.evex                    = null;
mnemonic_add_26.mode                    = 12;
mnemonic_add_26.extensions              = null;

const mnemonic_add_27 = new MnemonicX86;
mnemonic_add_27.mnemonic                = "mov";
mnemonic_add_27.operandSize             = 32;
mnemonic_add_27.opcode                  = 3875;
mnemonic_add_27.operandTemplates        = [[a.dr0, a.dr1, a.dr2, a.dr3, a.dr4, a.dr5, a.dr6, a.dr7], [a.r]];
mnemonic_add_27.opreg                   = -1;
mnemonic_add_27.operandSizeDefault      = 32;
mnemonic_add_27.lock                    = false;
mnemonic_add_27.regInOp                 = false;
mnemonic_add_27.opcodeDirectionBit      = true;
mnemonic_add_27.useModrm                = true;
mnemonic_add_27.rep                     = false;
mnemonic_add_27.repne                   = false;
mnemonic_add_27.prefixes                = null;
mnemonic_add_27.opEncoding              = "rm";
mnemonic_add_27.rex                     = null;
mnemonic_add_27.vex                     = null;
mnemonic_add_27.evex                    = null;
mnemonic_add_27.mode                    = 12;
mnemonic_add_27.extensions              = null;

const mnemonic_add_28 = new MnemonicX86;
mnemonic_add_28.mnemonic                = "mov";
mnemonic_add_28.operandSize             = 64;
mnemonic_add_28.opcode                  = 3873;
mnemonic_add_28.operandTemplates        = [[a.r], [a.dr0, a.dr1, a.dr2, a.dr3, a.dr4, a.dr5, a.dr6, a.dr7]];
mnemonic_add_28.opreg                   = -1;
mnemonic_add_28.operandSizeDefault      = 32;
mnemonic_add_28.lock                    = false;
mnemonic_add_28.regInOp                 = false;
mnemonic_add_28.opcodeDirectionBit      = true;
mnemonic_add_28.useModrm                = true;
mnemonic_add_28.rep                     = false;
mnemonic_add_28.repne                   = false;
mnemonic_add_28.prefixes                = null;
mnemonic_add_28.opEncoding              = "rm";
mnemonic_add_28.rex                     = null;
mnemonic_add_28.vex                     = null;
mnemonic_add_28.evex                    = null;
mnemonic_add_28.mode                    = 32;
mnemonic_add_28.extensions              = null;

const mnemonic_add_29 = new MnemonicX86;
mnemonic_add_29.mnemonic                = "mov";
mnemonic_add_29.operandSize             = 64;
mnemonic_add_29.opcode                  = 3875;
mnemonic_add_29.operandTemplates        = [[a.dr0, a.dr1, a.dr2, a.dr3, a.dr4, a.dr5, a.dr6, a.dr7], [a.r]];
mnemonic_add_29.opreg                   = -1;
mnemonic_add_29.operandSizeDefault      = 32;
mnemonic_add_29.lock                    = false;
mnemonic_add_29.regInOp                 = false;
mnemonic_add_29.opcodeDirectionBit      = true;
mnemonic_add_29.useModrm                = true;
mnemonic_add_29.rep                     = false;
mnemonic_add_29.repne                   = false;
mnemonic_add_29.prefixes                = null;
mnemonic_add_29.opEncoding              = "rm";
mnemonic_add_29.rex                     = null;
mnemonic_add_29.vex                     = null;
mnemonic_add_29.evex                    = null;
mnemonic_add_29.mode                    = 32;
mnemonic_add_29.extensions              = null;

const x86_mnemonic_variations_mov = new MnemonicVariationsX86([
    mnemonic_add_0,
    mnemonic_add_1,
    mnemonic_add_2,
    mnemonic_add_3,
    mnemonic_add_4,
    mnemonic_add_5,
    mnemonic_add_6,
    mnemonic_add_7,
    mnemonic_add_8,
    mnemonic_add_9,
    mnemonic_add_10,
    mnemonic_add_11,
    mnemonic_add_12,
    mnemonic_add_13,
    mnemonic_add_14,
    mnemonic_add_15,
    mnemonic_add_16,
    mnemonic_add_17,
    mnemonic_add_18,
    mnemonic_add_19,
    mnemonic_add_20,
    mnemonic_add_21,
    mnemonic_add_22,
    mnemonic_add_23,
    mnemonic_add_24,
    mnemonic_add_25,
    mnemonic_add_26,
    mnemonic_add_27,
    mnemonic_add_28,
    mnemonic_add_29,
]);
x86_mnemonic_variations_mov.defaultOperandSize = 32;

export default x86_mnemonic_variations_mov;
