"use strict";
var util_1 = require('../../util');
var o = require('../operand');
var t = require('../table');
var table_1 = require('../../table');
var table_2 = require('../table');
exports.cr0_7 = [o.cr(0), o.cr(1), o.cr(2), o.cr(3), o.cr(4), o.cr(5), o.cr(6), o.cr(7)];
exports.dr0_7 = [o.dr(0), o.dr(1), o.dr(2), o.dr(3), o.dr(4), o.dr(5), o.dr(6), o.dr(7)];
exports.defaults = util_1.extend({}, t.defaults, { rex: false, ds: table_1.S.D });
function tpl_and(o_al, o_imm, or_imm, o_reg, lock) {
    if (o_al === void 0) { o_al = 0x24; }
    if (o_imm === void 0) { o_imm = 0x80; }
    if (or_imm === void 0) { or_imm = 4; }
    if (o_reg === void 0) { o_reg = 0x20; }
    if (lock === void 0) { lock = true; }
    return [{ lock: lock },
        { o: o_al, ops: [o.al, table_1.imm8], mr: false },
        { o: o_al + 1, ops: [o.ax, table_1.imm16], mr: false },
        { o: o_al + 1, ops: [o.eax, table_1.imm32], mr: false },
        { o: o_al + 1, ops: [o.rax, table_1.imm32], mr: false },
        { o: o_imm, or: or_imm, ops: [table_2.rm8, table_1.imm8] },
        { o: o_imm + 1, or: or_imm, ops: [table_2.rm16, table_1.imm16] },
        { o: o_imm + 1, or: or_imm, ops: [table_2.rm32, table_1.imm32] },
        { o: o_imm + 1, or: or_imm, ops: [table_2.rm64, table_1.imm32] },
        { o: o_imm + 3, or: or_imm, ops: [table_2.rm16, table_1.imm8] },
        { o: o_imm + 3, or: or_imm, ops: [table_2.rm32, table_1.imm8] },
        { o: o_imm + 3, or: or_imm, ops: [table_2.rm64, table_1.imm8] },
        { o: o_reg, ops: [table_2.rm8, table_2.r8], en: 'mr', dbit: true },
        { o: o_reg + 2, ops: [table_2.r8, table_2.rm8], dbit: true },
        { o: o_reg + 1, ops: [table_2.rm16, table_2.r16], en: 'mr', dbit: true },
        { o: o_reg + 3, ops: [table_2.r16, table_2.rm16], dbit: true },
        { o: o_reg + 1, ops: [table_2.rm32, table_2.r32], en: 'mr', dbit: true },
        { o: o_reg + 3, ops: [table_2.r32, table_2.rm32], dbit: true },
        { o: o_reg + 1, ops: [table_2.rm64, table_2.r64], en: 'mr', dbit: true },
        { o: o_reg + 3, ops: [table_2.r64, table_2.rm64], dbit: true },
    ];
}
function tpl_not(o, or, lock) {
    if (o === void 0) { o = 0xF6; }
    if (or === void 0) { or = 2; }
    if (lock === void 0) { lock = true; }
    return [{ o: o + 1, or: or, lock: lock },
        { o: o, ops: [table_2.rm8] },
        { ops: [table_2.rm16] },
        { ops: [table_2.rm32] },
        { ops: [table_2.rm64] },
    ];
}
function tpl_sar(or, o_r, o_imm) {
    if (or === void 0) { or = 7; }
    if (o_r === void 0) { o_r = 0xD0; }
    if (o_imm === void 0) { o_imm = 0xC0; }
    return [{ or: or },
        { o: o_r, ops: [table_2.rm8, 1] },
        { o: o_r + 2, ops: [table_2.rm8, o.cl], s: table_1.S.B },
        { o: o_imm, ops: [table_2.rm8, table_1.imm8] },
        { o: o_r + 1, ops: [table_2.rm16, 1] },
        { o: o_r + 3, ops: [table_2.rm16, o.cl], s: table_1.S.W },
        { o: o_imm + 1, ops: [table_2.rm16, table_1.imm8] },
        { o: o_r + 1, ops: [table_2.rm32, 1] },
        { o: o_r + 1, ops: [table_2.rm64, 1] },
        { o: o_r + 3, ops: [table_2.rm32, o.cl], s: table_1.S.D },
        { o: o_r + 3, ops: [table_2.rm64, o.cl], s: table_1.S.Q },
        { o: o_imm + 1, ops: [table_2.rm32, table_1.imm8] },
        { o: o_imm + 1, ops: [table_2.rm64, table_1.imm8] },
    ];
}
function tpl_shrd(op) {
    if (op === void 0) { op = 0x0FAC; }
    return [{},
        { o: op, ops: [table_2.rm16, table_2.r16, table_1.imm8] },
        { o: op + 1, ops: [table_2.rm16, table_2.r16, o.cl], s: table_1.S.W },
        { o: op, ops: [table_2.rm32, table_2.r32, table_1.imm8] },
        { o: op, ops: [table_2.rm64, table_2.r64, table_1.imm8] },
        { o: op + 1, ops: [table_2.rm32, table_2.r32, o.cl], s: table_1.S.D },
        { o: op + 1, ops: [table_2.rm64, table_2.r64, o.cl], s: table_1.S.Q },
    ];
}
function tpl_bt(o_r, or_imm, o_imm) {
    if (o_r === void 0) { o_r = 0x0FA3; }
    if (or_imm === void 0) { or_imm = 4; }
    if (o_imm === void 0) { o_imm = 0x0FBA; }
    return [{ en: 'mr' },
        { o: o_r, ops: [table_2.rm16, table_2.r16] },
        { o: o_r, ops: [table_2.rm32, table_2.r32] },
        { o: o_r, ops: [table_2.rm64, table_2.r64] },
        { o: o_imm, or: or_imm, ops: [table_2.rm16, table_1.imm8] },
        { o: o_imm, or: or_imm, ops: [table_2.rm32, table_1.imm8] },
        { o: o_imm, or: or_imm, ops: [table_2.rm64, table_1.imm8] },
    ];
}
function tpl_bsf(op) {
    if (op === void 0) { op = 0x0FBC; }
    return [{ o: op },
        { ops: [table_2.r16, table_2.rm16] },
        { ops: [table_2.r32, table_2.rm32] },
        { ops: [table_2.r64, table_2.rm64] },
    ];
}
function tpl_ja(op, op2) {
    if (op === void 0) { op = 0x77; }
    if (op2 === void 0) { op2 = 0x0F87; }
    return [{},
        { o: op, ops: [table_1.rel8] },
        { o: op2, ops: [table_1.rel32] },
    ];
}
function tpl_cmovc(op) {
    if (op === void 0) { op = 0x0F42; }
    return [{ o: op },
        { ops: [table_2.r16, table_2.rm16] },
        { ops: [table_2.r32, table_2.rm32] },
        { ops: [table_2.r64, table_2.rm64] },
    ];
}
function tpl_xadd(op, lock) {
    if (op === void 0) { op = 0; }
    if (lock === void 0) { lock = true; }
    return [{ o: op + 1, lock: lock },
        { o: op, ops: [table_2.rm8, table_2.r8] },
        { ops: [table_2.rm16, table_2.r16] },
        { ops: [table_2.rm32, table_2.r32] },
        { ops: [table_2.rm64, table_2.r64] },
    ];
}
function tpl_movs(op) {
    if (op === void 0) { op = 0xA4; }
    return [{ o: op + 1 },
        { o: op, s: table_1.S.B },
        { s: table_1.S.W },
        { s: table_1.S.D },
        { s: table_1.S.Q },
    ];
}
function tpl_lss(op) {
    if (op === void 0) { op = 0x0FB2; }
    return [{ o: op },
        { ops: [table_2.rm16, table_2.m] },
        { ops: [table_2.rm32, table_2.m] },
        { ops: [table_2.rm64, table_2.m] },
    ];
}
function tpl_blsi(op, or) {
    if (op === void 0) { op = 0xF3; }
    if (or === void 0) { or = 3; }
    return [{ o: op, or: or, en: 'vm', ext: [table_2.EXT.BMI1] },
        { vex: 'NDD.LZ.0F38.W0', ops: [table_2.r32, table_2.rm32] },
        { vex: 'NDD.LZ.0F38.W1', ops: [table_2.r64, table_2.rm64], mod: table_2.M.X64 },
    ];
}
function tpl_bndcl(op) {
    if (op === void 0) { op = 0xF30F1A; }
    return [{ o: op, ext: [table_2.EXT.MPX] },
        { ops: [table_2.bnd, table_2.rm32], mod: table_2.M.X32 },
        { ops: [table_2.bnd, table_2.rm64], mod: table_2.M.X64 },
    ];
}
var _dec = tpl_not(0xFE, 1);
_dec.push({ o: 0x48, r: true, ops: [table_2.r16], mod: table_2.M.COMP | table_2.M.LEG });
_dec.push({ o: 0x48, r: true, ops: [table_2.r32], mod: table_2.M.COMP | table_2.M.LEG });
var _inc = tpl_not(0xFE, 0);
_inc.push({ o: 0x40, r: true, ops: [table_2.r16], mod: table_2.M.COMP | table_2.M.LEG });
_inc.push({ o: 0x40, r: true, ops: [table_2.r32], mod: table_2.M.COMP | table_2.M.LEG });
exports.table = util_1.extend({}, t.table, {
    aaa: [{ o: 0x37, mod: table_2.M.OLD }],
    aad: [{ mod: table_2.M.OLD },
        { o: 0xD50A },
        { o: 0xD5, ops: [table_1.imm8] },
    ],
    aam: [{ mod: table_2.M.OLD },
        { o: 0xD40A },
        { o: 0xD4, ops: [table_1.imm8] },
    ],
    aas: [{ o: 0x3F, mod: table_2.M.OLD }],
    addpd: [{ o: 0x660F58, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vaddpd: [{ o: 0x58, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    addps: [{ o: 0x0F58, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vaddps: [{ o: 0x58, en: 'rvm' },
        { vex: 'NDS.128.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] },
        { vex: 'NDS.256.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]], ext: [table_2.EXT.AVX] },
        { evex: 'NDS.128.0F.W0', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX512VL, table_2.EXT.AVX512F] },
        { evex: 'NDS.256.0F.W0', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]], ext: [table_2.EXT.AVX512VL, table_2.EXT.AVX512F] },
        { evex: 'NDS.512.0F.W0', ops: [table_2.zmm, table_2.zmm, [table_2.zmm, table_2.m]], ext: [table_2.EXT.AVX512F] },
    ],
    kandw: [{},
        { o: 0x41, vex: 'L1.0F.W0', ops: [], ext: [table_2.EXT.AVX512F] },
    ],
    addsd: [{ o: 0xF20F58, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vaddsd: [{ o: 0x58, vex: 'NDS.LIG.F2.0F.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] }],
    addss: [{ o: 0xF30F58, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vaddss: [{ o: 0x58, vex: 'NDS.LIG.F3.0F.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] }],
    addsubpd: [{ o: 0x660FD0, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE3] }],
    vaddsubpd: [{ o: 0xD0, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    addsubps: [{ o: 0xF20FD0, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE3] }],
    vaddsubps: [{ o: 0xD0, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.F2.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.F2.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    aesdec: [{ o: 0x0F38DE, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES] }],
    vaesdec: [{ o: 0xDE, vex: 'NDS.128.66.0F38.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES, table_2.EXT.AVX] }],
    aesdeclast: [{ o: 0x0F38DF, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES] }],
    vaesdeclast: [{ o: 0xDF, vex: 'NDS.128.66.0F38.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES, table_2.EXT.AVX] }],
    aesenc: [{ o: 0x0F38DC, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES] }],
    vaesenc: [{ o: 0xDC, vex: 'NDS.128.66.0F38.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES, table_2.EXT.AVX] }],
    aesenclast: [{ o: 0x0F38DD, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES] }],
    vaesenclast: [{ o: 0xDD, vex: 'NDS.128.66.0F38.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES, table_2.EXT.AVX] }],
    aesimc: [{ o: 0x0F38DB, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES] }],
    vaesimc: [{ o: 0xDB, vex: '128.66.0F38.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AES, table_2.EXT.AVX] }],
    aeskeygenassist: [{ o: 0x0F3ADF, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.AES] }],
    vaeskeygenassist: [{ o: 0xDF, vex: '128.66.0F3A.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.AES, table_2.EXT.AVX] }],
    andn: [{ o: 0xF2, en: 'rvm', ext: [table_2.EXT.BMI1] },
        { vex: 'NDS.LZ.0F38.W0', ops: [table_2.r32, table_2.r32, table_2.rm32] },
        { vex: 'NDS.LZ.0F38.W1', ops: [table_2.r64, table_2.r64, table_2.rm64], mod: table_2.M.X64 },
    ],
    andpd: [{ o: 0x660F54, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vandpd: [{ o: 0x54, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    andps: [{ o: 0x0F54, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vandps: [{ o: 0x54, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    andnpd: [{ o: 0x660F55, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vandnpd: [{ o: 0x55, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    andnps: [{ o: 0x0F55, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vandnps: [{ o: 0x55, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    arpl: [{ o: 0x63, ops: [table_2.rm16, table_2.r16], mod: table_2.M.OLD }],
    blendpd: [{ o: 0x0F3A0F, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE4_1] }],
    vblendpd: [{ o: 0x0D, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F3A.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8] },
        { vex: 'NDS.256.66.0F3A.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m], table_1.imm8] },
    ],
    bextr: [{ o: 0xF7, en: 'rmv', ext: [table_2.EXT.BMI1] },
        { vex: 'NDS.LZ.0F38.W0', ops: [table_2.r32, table_2.rm32, table_2.r32] },
        { vex: 'NDS.LZ.0F38.W1', ops: [table_2.r64, table_2.rm64, table_2.r64], mod: table_2.M.X64 },
    ],
    blendps: [{ o: 0x0F3A0C, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE4_1] }],
    vblendps: [{ o: 0x0C, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F3A.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8] },
        { vex: 'NDS.256.66.0F3A.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m], table_1.imm8] },
    ],
    blendvpd: [{ o: 0x0F3815, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE4_1] }],
    vblendvpd: [{ o: 0x4B, en: 'rvmr', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F3A.W0', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_2.xmm] },
        { vex: 'NDS.256.66.0F3A.W0', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m], table_2.ymm] },
    ],
    blendvps: [{ o: 0x0F3814, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE4_1] }],
    vblendvps: [{ o: 0x4A, en: 'rvmr', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F3A.W0', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_2.xmm] },
        { vex: 'NDS.256.66.0F3A.W0', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m], table_2.ymm] },
    ],
    blsi: tpl_blsi(),
    blsmsk: tpl_blsi(0xF3, 2),
    blsr: tpl_blsi(0xF3, 1),
    bndcl: tpl_bndcl(),
    bndcu: tpl_bndcl(0xF20F1A),
    bndcn: tpl_bndcl(0xF20F1B),
    bndmk: tpl_bndcl(0xF30F1B),
    bndldx: [{ o: 0x0F1A, ops: [table_2.bnd, table_2.m], ext: [table_2.EXT.MPX] }],
    bndmov: [{ pfx: [0x66, 0x0F], ext: [table_2.EXT.MPX] },
        { o: 0x1A, ops: [table_2.bnd, [table_2.bnd, table_2.m]], dbit: true },
        { o: 0x1B, ops: [[table_2.bnd, table_2.m], table_2.bnd], en: 'mr', dbit: true },
    ],
    bndstx: [{ o: 0x0F1B, ops: [table_2.m, table_2.bnd], en: 'mr', ext: [table_2.EXT.MPX] }],
    bound: [{ o: 0x62, mod: table_2.M.OLD },
        { ops: [table_2.r16, table_2.m] },
        { ops: [table_2.r32, table_2.m] },
    ],
    bzhi: [{ o: 0xF5, en: 'rmv', ext: [table_2.EXT.BMI2] },
        { vex: 'NDS.LZ.0F38.W0', ops: [table_2.r32, table_2.rm32, table_2.r32] },
        { vex: 'NDS.LZ.0F38.W1', ops: [table_2.r64, table_2.rm64, table_2.r64], mod: table_2.M.X64 },
    ],
    clflush: [{ o: 0x0FAE, or: 7, ops: [table_2.m] }],
    clflushopt: [{ o: 0x660FAE, or: 7, ops: [table_2.m] }],
    clts: [{ o: 0x0F06 }],
    cmppd: [{ o: 0x660FC2, ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE2] }],
    vcmppd: [{ o: 0xC2, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m], table_1.imm8] },
    ],
    cmpps: [{ o: 0x0FC2, ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE] }],
    vcmpps: [{ o: 0xC2, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.0F.WIG C2', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8] },
        { vex: 'NDS.256.0F.WIG C2', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m], table_1.imm8] },
    ],
    cmpsd: [{ o: 0xF20FC2, ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE2] }],
    vcmpsd: [{ o: 0xC2, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.LIG.F2.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8] },
    ],
    cmpss: [{ o: 0xF30FC2, ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE] }],
    vcmpss: [{ o: 0xC2, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.LIG.F3.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8] },
    ],
    comisd: [{ o: 0x660F2F, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcomisd: [{ o: 0x2F, vex: 'LIG.66.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] }],
    comiss: [{ o: 0x0F2F, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vcomiss: [{ o: 0x2F, vex: 'LIG.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] }],
    cvtdq2pd: [{ o: 0xF30FE6, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtdq2pd: [{ o: 0xE6, ext: [table_2.EXT.AVX] },
        { vex: '128.F3.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.F3.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    cvtdq2ps: [{ o: 0x0F5B, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtdq2ps: [{ o: 0x5B, ext: [table_2.EXT.AVX] },
        { vex: '128.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    cvtpd2dq: [{ o: 0xF20FE6, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtpd2dq: [{ o: 0xE6, ext: [table_2.EXT.AVX] },
        { vex: '128.F2.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.F2.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    cvtpd2pi: [{ o: 0x660F2D, ops: [table_2.xmm, [table_2.xmm, table_2.m]] }],
    cvtpd2ps: [{ o: 0x660F5A, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtpd2ps: [{ o: 0x5A, ext: [table_2.EXT.AVX] },
        { vex: '128.66.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.66.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    cvtpi2pd: [{ o: 0x660F2A, ops: [table_2.xmm, [table_2.xmm, table_2.m]] }],
    cvtpi2ps: [{ o: 0x0F2A, ops: [table_2.xmm, [table_2.xmm, table_2.m]] }],
    cvtps2dq: [{ o: 0x660F5B, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtps2dq: [{ o: 0x5B, ext: [table_2.EXT.AVX] },
        { vex: '128.66.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.66.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    cvtps2pd: [{ o: 0x0F5A, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtps2pd: [{ o: 0x5A, ext: [table_2.EXT.AVX] },
        { vex: '128.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    cvtps2pi: [{ o: 0x0F2D, ops: [table_2.xmm, [table_2.xmm, table_2.m]] }],
    cvtsd2si: [{ o: 0xF20F2D, ops: [table_2.r32, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtsd2si: [{ o: 0x2D, ext: [table_2.EXT.AVX] },
        { o: 0x0F2D, pfx: [0xF2], ops: [table_2.r64, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2], mod: table_2.M.X64 },
        { vex: 'LIG.F2.0F.W0', ops: [table_2.r32, [table_2.xmm, table_2.m]] },
        { vex: 'LIG.F2.0F.W1', ops: [table_2.r64, [table_2.xmm, table_2.m]], mod: table_2.M.X64 },
    ],
    cvtsd2ss: [{ o: 0xF20F5A, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtsd2ss: [{ o: 0x5A, vex: 'NDS.LIG.F2.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], en: 'rvm', ext: [table_2.EXT.AVX] }],
    cvtsi2sd: [{ o: 0x0F2A, pfx: [0xF2], ext: [table_2.EXT.SSE2] },
        { ops: [table_2.xmm, table_2.rm32] },
        { ops: [table_2.xmm, table_2.rm64] },
    ],
    vcvtsi2sd: [{ o: 0x2A, ext: [table_2.EXT.AVX], en: 'rvm' },
        { vex: 'NDS.LIG.F2.0F.W0', ops: [table_2.xmm, table_2.xmm, table_2.rm32] },
        { vex: 'NDS.LIG.F2.0F.W1', ops: [table_2.xmm, table_2.xmm, table_2.rm64] },
    ],
    cvtsi2ss: [{ o: 0x0F2A, pfx: [0xF3], ext: [table_2.EXT.SSE] },
        { ops: [table_2.xmm, table_2.rm32] },
        { ops: [table_2.xmm, table_2.rm64] },
    ],
    vcvtsi2ss: [{ o: 0x2A, ext: [table_2.EXT.AVX], en: 'rvm' },
        { vex: 'NDS.LIG.F3.0F.W0', ops: [table_2.xmm, table_2.xmm, table_2.rm32] },
        { vex: 'NDS.LIG.F3.0F.W1', ops: [table_2.xmm, table_2.xmm, table_2.rm64] },
    ],
    cvtss2sd: [{ o: 0xF30F5A, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvtss2sd: [{ o: 0x5A, vex: 'NDS.LIG.F3.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], en: 'rvm', ext: [table_2.EXT.AVX] }],
    cvtss2si: [{ o: 0x0F2D, pfx: [0xF3], ext: [table_2.EXT.SSE] },
        { ops: [table_2.r32, [table_2.xmm, table_2.m]] },
        { ops: [table_2.r64, [table_2.xmm, table_2.m]], mod: table_2.M.X64 },
    ],
    vcvtss2si: [{ o: 0x2D, ext: [table_2.EXT.AVX] },
        { vex: 'LIG.F3.0F.W0', ops: [table_2.r32, [table_2.xmm, table_2.m]] },
        { vex: 'LIG.F3.0F.W1', ops: [table_2.r64, [table_2.xmm, table_2.m]], mod: table_2.M.X64 },
    ],
    cvttpd2dq: [{ o: 0x660FE6, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvttpd2dq: [{ o: 0xE6, ext: [table_2.EXT.AVX] },
        { vex: '128.66.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.66.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    cvttpd2pi: [{ o: 0x660F2C, ops: [table_2.xmm, [table_2.xmm, table_2.m]] }],
    cvttps2dq: [{ o: 0xF30F5B, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vcvttps2dq: [{ o: 0x5B, ext: [table_2.EXT.AVX] },
        { vex: '128.F3.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.F3.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    cvttps2pi: [{ o: 0x0F2C, ops: [table_2.xmm, [table_2.xmm, table_2.m]] }],
    cvttsd2si: [{ o: 0x0F2C, pfx: [0xF2], ext: [table_2.EXT.SSE2] },
        { ops: [table_2.r32, [table_2.xmm, table_2.m]] },
        { ops: [table_2.r64, [table_2.xmm, table_2.m]], mod: table_2.M.X64 },
    ],
    vcvttsd2si: [{ o: 0x2C, ext: [table_2.EXT.AVX] },
        { vex: 'LIG.F2.0F.W0', ops: [table_2.r32, [table_2.xmm, table_2.m]] },
        { vex: 'LIG.F2.0F.W1', ops: [table_2.r64, [table_2.xmm, table_2.m]], mod: table_2.M.X64 },
    ],
    cvttss2si: [{ o: 0x0F2C, pfx: [0xF3], ext: [table_2.EXT.SSE] },
        { ops: [table_2.r32, [table_2.xmm, table_2.m]] },
        { ops: [table_2.r64, [table_2.xmm, table_2.m]], mod: table_2.M.X64 },
    ],
    vcvttss2si: [{ o: 0x2C, ext: [table_2.EXT.AVX] },
        { vex: 'LIG.F3.0F.W0', ops: [table_2.r32, [table_2.xmm, table_2.m]] },
        { vex: 'LIG.F3.0F.W1', ops: [table_2.r64, [table_2.xmm, table_2.m]], mod: table_2.M.X64 },
    ],
    daa: [{ o: 0x27, mod: table_2.M.OLD }],
    das: [{ o: 0x2F, mod: table_2.M.OLD }],
    divpd: [{ o: 0x660F5E, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vdivpd: [{ o: 0x5E, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    divps: [{ o: 0x0F5E, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vdivps: [{ o: 0x5E, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    divsd: [{ o: 0xF20F5E, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vdivsd: [{ o: 0x5E, en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.LIG.F2.0F.WIG', ext: [table_2.EXT.AVX] },
        { evex: 'NDS.LIG.F2.0F.W1', ext: [table_2.EXT.AVX512F] },
    ],
    divss: [{ o: 0xF30F5E, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vdivss: [{ o: 0x5E, en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.LIG.F3.0F.WIG', ext: [table_2.EXT.AVX] },
    ],
    dppd: [{ o: 0x0F3A41, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE4_1] }],
    vdppd: [{ o: 0x41, vex: 'NDS.128.66.0F3A.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.AVX] }],
    dpps: [{ o: 0x0F3A40, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE4_1] }],
    vdpps: [{ o: 0x40, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F3A.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8] },
        { vex: 'NDS.256.66.0F3A.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m], table_1.imm8] },
    ],
    emms: [{ o: 0x0F77 }],
    extractps: [{ o: 0x0F3A17, pfx: [0x66], en: 'mr', ops: [table_2.r32, table_2.xmm, table_1.imm8], ext: [table_2.EXT.SSE4_1] }],
    vextractps: [{ o: 0x17, en: 'mr', vex: '128.66.0F3A.WIG', ops: [table_2.rm32, table_2.xmm, table_1.imm8], ext: [table_2.EXT.AVX] }],
    f2xm1: [{ o: 0xD9F0 }],
    fabs: [{ o: 0xD9E1 }],
    fadd: [{},
        { o: 0xD8, or: 0, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDC, or: 0, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xD8, ops: [o.st(0), table_2.st] },
        { o: 0xDC, ops: [table_2.st, o.st(0)] },
    ],
    faddp: [{},
        { o: 0xDE, ops: [table_2.st, o.st(0)] },
        { o: 0xDEC1 },
    ],
    fiadd: [{ or: 0 },
        { o: 0xDA, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDE, ops: [table_2.m], s: table_1.S.W },
    ],
    fbld: [{ o: 0xDF, or: 4, ops: [table_2.m] }],
    fbstp: [{ o: 0xDF, or: 6, ops: [table_2.m] }],
    fchs: [{ o: 0xD9E0 }],
    fclex: [{ o: 0x9BDBE2 }],
    fnclex: [{ o: 0xDBE2 }],
    fcmovb: [{ o: 0xDA, or: 0, ops: [table_2.st] }],
    fcmove: [{ o: 0xDA, or: 1, ops: [table_2.st] }],
    fcmovbe: [{ o: 0xDA, or: 2, ops: [table_2.st] }],
    fcmovu: [{ o: 0xDA, or: 3, ops: [table_2.st] }],
    fcmovnb: [{ o: 0xDB, or: 0, ops: [table_2.st] }],
    fcmovne: [{ o: 0xDB, or: 1, ops: [table_2.st] }],
    fcmovnbe: [{ o: 0xDB, or: 2, ops: [table_2.st] }],
    fcmovnu: [{ o: 0xDB, or: 3, ops: [table_2.st] }],
    fcom: [{ or: 2 },
        { o: 0xD8, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDC, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xD8, ops: [table_2.st] },
        { o: 0xD8D1 },
    ],
    fcomp: [{ or: 3 },
        { o: 0xD8, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDC, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xD8, ops: [table_2.st] },
        { o: 0xD8D9 },
    ],
    fcompp: [{ o: 0xDED9 }],
    fcomi: [{ o: 0xDB, or: 6, ops: [table_2.st] }],
    fcomip: [{ o: 0xDF, or: 6, ops: [table_2.st] }],
    fucomi: [{ o: 0xDB, or: 5, ops: [table_2.st] }],
    fucomip: [{ o: 0xDF, or: 5, ops: [table_2.st] }],
    fcos: [{ o: 0xD9FF }],
    fdecstp: [{ o: 0xD9F6 }],
    fdiv: [{},
        { o: 0xD8, or: 6, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDC, or: 6, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xD8, i: 0xF0, ops: [o.st(0), table_2.st] },
        { o: 0xDC, i: 0xF8, ops: [table_2.st, o.st(0)] },
    ],
    fdivp: [{},
        { o: 0xDE, i: 0xF8, ops: [table_2.st, o.st(0)] },
        { o: 0xDEF9 },
    ],
    fidiv: [{ or: 6 },
        { o: 0xDA, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDE, ops: [table_2.m], s: table_1.S.W },
    ],
    fdivr: [{},
        { o: 0xD8, or: 7, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDC, or: 7, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xD8, i: 0xF8, ops: [o.st(0), table_2.st] },
        { o: 0xDC, i: 0xF0, ops: [table_2.st, o.st(0)] },
    ],
    fdivrp: [{ o: 0xDE },
        { i: 0xF0, ops: [table_2.st, o.st(0)] },
        { i: 0xF1 },
    ],
    fidivr: [{ or: 7 },
        { o: 0xDA, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDE, ops: [table_2.m], s: table_1.S.W },
    ],
    ffree: [{ o: 0xDD, i: 0xC0, ops: [table_2.st] }],
    ficom: [{ or: 2 },
        { o: 0xDE, ops: [table_2.m], s: table_1.S.W },
        { o: 0xDA, ops: [table_2.m], s: table_1.S.D },
    ],
    ficomp: [{ or: 3 },
        { o: 0xDE, ops: [table_2.m], s: table_1.S.W },
        { o: 0xDA, ops: [table_2.m], s: table_1.S.D },
    ],
    fild: [{},
        { o: 0xDF, or: 0, ops: [table_2.m], s: table_1.S.W },
        { o: 0xDB, or: 0, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDF, or: 5, ops: [table_2.m], s: table_1.S.Q },
    ],
    fincstp: [{ o: 0xD9F7 }],
    finit: [{ o: 0x9BDBE3 }],
    fninit: [{ o: 0xDBE3 }],
    fist: [{ or: 2, ops: [table_2.m] },
        { o: 0xDF, s: table_1.S.W },
        { o: 0xDB, s: table_1.S.D },
    ],
    fistp: [{ ops: [table_2.m] },
        { o: 0xDF, or: 3, s: table_1.S.W },
        { o: 0xDB, or: 3, s: table_1.S.D },
        { o: 0xDF, or: 7, s: table_1.S.Q },
    ],
    fisttp: [{ or: 1, ops: [table_2.m] },
        { o: 0xDF, s: table_1.S.W },
        { o: 0xDB, s: table_1.S.D },
        { o: 0xDD, s: table_1.S.Q },
    ],
    fld: [{},
        { o: 0xD9, or: 0, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDD, or: 0, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xDB, or: 5, ops: [table_2.m], s: table_1.S.T },
        { o: 0xD9, i: 0xC0, ops: [table_2.st] },
    ],
    fld1: [{ o: 0xD9E8 }],
    fldl2t: [{ o: 0xD9E9 }],
    fldl2e: [{ o: 0xD9EA }],
    fldpi: [{ o: 0xD9EB }],
    fldlg2: [{ o: 0xD9EC }],
    fldln2: [{ o: 0xD9ED }],
    fldz: [{ o: 0xD9EE }],
    fldcw: [{ o: 0xD9, or: 5, ops: [table_2.m], s: table_1.S.W }],
    fldenv: [{ o: 0xD9, or: 4, ops: [table_2.m] }],
    fmul: [{},
        { o: 0xD8, or: 1, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDC, or: 1, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xD8, i: 0xC8, ops: [o.st(0), table_2.st] },
        { o: 0xDC, i: 0xC8, ops: [table_2.st, o.st(0)] },
    ],
    fmulp: [{},
        { o: 0xDE, i: 0xC8, ops: [table_2.st, o.st(0)] },
        { o: 0xDEC9 },
    ],
    fimul: [{ or: 1 },
        { o: 0xDA, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDE, ops: [table_2.m], s: table_1.S.Q },
    ],
    fnop: [{ o: 0xD9D0 }],
    fpatan: [{ o: 0xD9F3 }],
    fprem: [{ o: 0xD9F8 }],
    fprem1: [{ o: 0xD9F5 }],
    fptan: [{ o: 0xD9F2 }],
    frndint: [{ o: 0xD9FC }],
    frstor: [{ o: 0xDD, or: 4, ops: [table_2.m] }],
    fsave: [{ o: 0x9BDD, or: 6, ops: [table_2.m] }],
    fnsave: [{ o: 0xDD, or: 6, ops: [table_2.m] }],
    fscale: [{ o: 0xD9FD }],
    fsin: [{ o: 0xD9FE }],
    fsincos: [{ o: 0xD9FB }],
    fsqrt: [{ o: 0xD9FA }],
    fst: [{},
        { o: 0xD9, or: 2, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDD, or: 2, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xDD, i: 0xD0, ops: [table_2.st] },
    ],
    fstp: [{},
        { o: 0xD9, or: 3, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDD, or: 3, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xDB, or: 7, ops: [table_2.m], s: table_1.S.T },
        { o: 0xDD, i: 0xD8, ops: [table_2.st] },
    ],
    fstcw: [{ o: 0x9BD9, or: 7, ops: [table_2.m], s: table_1.S.W }],
    fnstcw: [{ o: 0xD9, or: 7, ops: [table_2.m], s: table_1.S.W }],
    fstenv: [{ o: 0x9BD9, or: 6, ops: [table_2.m] }],
    fnstenv: [{ o: 0xD9, or: 6, ops: [table_2.m] }],
    fstsw: [{},
        { o: 0x9BDD, or: 7, ops: [table_2.m], s: table_1.S.W },
        { o: 0x9BDFE0, mr: false, ops: [o.ax] },
    ],
    fnstsw: [{},
        { o: 0xDD, or: 7, ops: [table_2.m], s: table_1.S.W },
        { o: 0xDFE0, mr: false, ops: [o.ax] },
    ],
    fsub: [{},
        { o: 0xD8, or: 4, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDC, or: 4, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xD8, i: 0xE0, ops: [o.st(0), table_2.st] },
        { o: 0xDC, i: 0xE8, ops: [table_2.st, o.st(0)] },
    ],
    fsubp: [{},
        { o: 0xDE, i: 0xE8, ops: [table_2.st, o.st(0)] },
        { o: 0xDEE9 },
    ],
    fisub: [{ or: 4 },
        { o: 0xDA, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDE, ops: [table_2.m], s: table_1.S.W },
    ],
    fsubr: [{},
        { o: 0xD8, or: 5, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDC, or: 5, ops: [table_2.m], s: table_1.S.Q },
        { o: 0xD8, i: 0xE8, ops: [o.st(0), table_2.st] },
        { o: 0xDC, i: 0xE0, ops: [table_2.st, o.st(0)] },
    ],
    fsubrp: [{},
        { o: 0xDE, i: 0xE0, ops: [table_2.st, o.st(0)] },
        { o: 0xDEE1 },
    ],
    fisubr: [{ or: 5 },
        { o: 0xDA, ops: [table_2.m], s: table_1.S.D },
        { o: 0xDE, ops: [table_2.m], s: table_1.S.W },
    ],
    ftst: [{ o: 0xD9E4 }],
    fucom: [{ o: 0xDD, i: 0xE0, ops: [table_2.st] }],
    fucomp: [{ o: 0xDD, i: 0xE8, ops: [table_2.st] }],
    fucompp: [{ o: 0xDAE9 }],
    fxam: [{ o: 0xD9E5 }],
    fxch: [{ o: 0xD9, i: 0xC8, ops: [table_2.st] }],
    fxrstor: [{ o: 0x0FAE, or: 1, ops: [table_2.m], s: 512 }],
    fxrstor64: [{ o: 0x0FAE, or: 1, ops: [table_2.m], s: 512, mod: table_2.M.X64 }],
    fxsave: [{ o: 0x0FAE, or: 0, ops: [table_2.m], s: 512 }],
    fxsave64: [{ o: 0x0FAE, or: 0, ops: [table_2.m], s: 512, mod: table_2.M.X64 }],
    fxtract: [{ o: 0xD9F4 }],
    fyl2x: [{ o: 0xD9F1 }],
    fyl2xp1: [{ o: 0xD9F9 }],
    haddpd: [{ o: 0x660F7C, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE3] }],
    vhaddpd: [{ o: 0x7C, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    haddps: [{ o: 0xF20F7C, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE3] }],
    vhaddps: [{ o: 0x7C, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.F2.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.F2.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    hlt: [{ o: 0xF4 }],
    hsubpd: [{ o: 0x660F7D, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE3] }],
    vhsubpd: [{ o: 0x7D, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    hsubps: [{ o: 0xF20F7D, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE3] }],
    vhsubps: [{ o: 0x7D, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.F2.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.F2.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    insertps: [{ o: 0x0F3A21, pfx: [0x66], ops: [table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.SSE4_1] }],
    vinsertps: [{ o: 0x21, vex: 'NDS.128.66.0F3A.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m], table_1.imm8], ext: [table_2.EXT.AVX] }],
    invd: [{ o: 0x0F08 }],
    invlpg: [{ o: 0x0F01, or: 7, ops: [table_2.m] }],
    invpcid: [{ o: 0x3882, pfx: [0x66, 0x0F], ext: [table_2.EXT.INVPCID] },
        { ops: [table_2.r32, table_2.m], mod: table_2.M.X32 },
        { ops: [table_2.r64, table_2.m], mod: table_2.M.X64 },
    ],
    lahf: [{ o: 0x9F, mod: table_2.M.COMP | table_2.M.LEG }],
    lar: [{ o: 0x0F02 },
        { ops: [table_2.r16, table_2.rm16] },
        { ops: [table_2.r, table_2.rm32] },
    ],
    lddqu: [{ o: 0xF20FF0, ops: [table_2.xmm, table_2.m], ext: [table_2.EXT.SSE3] }],
    vlddqu: [{ o: 0xF0, ext: [table_2.EXT.AVX] },
        { vex: '128.F2.0F.WIG', ops: [table_2.xmm, table_2.m] },
        { vex: '256.F2.0F.WIG', ops: [table_2.ymm, table_2.m] },
    ],
    ldmxcsr: [{ o: 0x0FAE, or: 2, ops: [table_2.m], s: table_1.S.D, ext: [table_2.EXT.SSE] }],
    vldmxcsr: [{ o: 0xAE, or: 2, vex: 'VEX.LZ.0F.WIG', ops: [table_2.m], ext: [table_2.EXT.AVX] }],
    lfence: [{ o: 0x0FAEE8 }],
    lgdt: [{ o: 0x0F01, or: 2 },
        { ops: [table_2.m] },
    ],
    lidt: [{ o: 0x0F01, or: 3 },
        { ops: [table_2.m] },
    ],
    lldt: [{ o: 0x0F00, or: 2, ops: [table_2.rm16] }],
    lmsw: [{ o: 0x0F01, or: 6, ops: [table_2.rm16] }],
    lock: [{ o: 0xF0 }],
    lsl: [{ o: 0x0F03 },
        { ops: [table_2.r16, table_2.rm16] },
        { ops: [table_2.r32, table_2.rm32] },
        { ops: [table_2.r64, table_2.rm32] },
    ],
    ltr: [{ o: 0x0F00, or: 3, ops: [table_2.rm16] }],
    lzcnt: [{ o: 0x0FBD, pfx: [0xF3], ext: [table_2.EXT.LZCNT] },
        { ops: [table_2.r16, table_2.rm16] },
        { ops: [table_2.r32, table_2.rm32] },
        { ops: [table_2.r64, table_2.rm64] },
    ],
    maskmovdqu: [{ o: 0x660FF7, ops: [table_2.xmm, table_2.xmm], ext: [table_2.EXT.SSE2] }],
    vmaskmovdqu: [{ o: 0xF7, vex: '128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm], ext: [table_2.EXT.AVX] }],
    maskmovq: [{ o: 0x0FF7, ops: [table_2.mm, table_2.mm] }],
    maxpd: [{ o: 0x660F5F, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vmaxpd: [{ o: 0x5F, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    maxps: [{ o: 0x0F5F, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vmaxps: [{ o: 0x5F, en: 'rvm', ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    maxsd: [{ o: 0xF20F5F, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vmaxsd: [{ o: 0x5F, vex: 'NDS.LIG.F2.0F.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] }],
    maxss: [{ o: 0xF30F5F, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vmaxss: [{ o: 0x5F, vex: 'NDS.LIG.F3.0F.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] }],
    mfence: [{ o: 0x0FAEF0 }],
    minpd: [{ o: 0x660F5D, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vminpd: [{ o: 0x5D, ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.66.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    minps: [{ o: 0x0F5D, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vminps: [{ o: 0x5D, ext: [table_2.EXT.AVX] },
        { vex: 'NDS.128.0F.WIG', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: 'NDS.256.0F.WIG', ops: [table_2.ymm, table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    minsd: [{ o: 0xF20F5D, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE2] }],
    vminsd: [{ o: 0x5D, vex: 'NDS.LIG.F2.0F.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] }],
    minss: [{ o: 0xF30F5D, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE] }],
    vminss: [{ o: 0x5D, vex: 'NDS.LIG.F3.0F.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.AVX] }],
    monitor: [{ o: 0x0F01C8 }],
    movapd: [{ pfx: [0x66, 0x0F], ext: [table_2.EXT.SSE2] },
        { o: 0x28, ops: [table_2.xmm, [table_2.xmm, table_2.m]], dbit: true },
        { o: 0x29, ops: [[table_2.xmm, table_2.m], table_2.xmm], dbit: true, en: 'mr' },
    ],
    vmovapd: [{ ext: [table_2.EXT.AVX] },
        { o: 0x28, vex: '128.66.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]], dbit: true },
        { o: 0x29, vex: '128.66.0F.WIG', ops: [[table_2.xmm, table_2.m], table_2.xmm], dbit: true, en: 'mr' },
        { o: 0x28, vex: '256.66.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]], dbit: true },
        { o: 0x29, vex: '256.66.0F.WIG', ops: [[table_2.ymm, table_2.m], table_2.ymm], dbit: true, en: 'mr' },
    ],
    movaps: [{ pfx: [0x0F], ext: [table_2.EXT.SSE] },
        { o: 0x28, ops: [table_2.xmm, [table_2.xmm, table_2.m]], dbit: true },
        { o: 0x29, ops: [[table_2.xmm, table_2.m], table_2.xmm], dbit: true, en: 'mr' },
    ],
    vmovaps: [{ ext: [table_2.EXT.AVX] },
        { o: 0x28, vex: '128.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]], dbit: true },
        { o: 0x29, vex: '128.0F.WIG', ops: [[table_2.xmm, table_2.m], table_2.xmm], dbit: true, en: 'mr' },
        { o: 0x28, vex: '256.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]], dbit: true },
        { o: 0x29, vex: '256.0F.WIG', ops: [[table_2.ymm, table_2.m], table_2.ymm], dbit: true, en: 'mr' },
    ],
    movd: [{},
        { o: 0x0F6E, ops: [table_2.mm, table_2.rm32], ext: [table_2.EXT.MMX] },
        { o: 0x0F7E, ops: [table_2.rm32, table_2.mm], ext: [table_2.EXT.MMX] },
        { o: 0x0F6E, pfx: [0x66], ops: [table_2.xmm, table_2.rm32], ext: [table_2.EXT.SSE2] },
        { o: 0x0F7E, pfx: [0x66], ops: [table_2.rm32, table_2.xmm], ext: [table_2.EXT.SSE2] },
    ],
    vmovd: [{ ext: [table_2.EXT.AVX] },
        { o: 0x6E, vex: '128.66.0F.W0', ops: [table_2.xmm, table_2.rm32] },
        { o: 0x7E, vex: '128.66.0F.W0', ops: [table_2.rm32, table_2.xmm] },
    ],
    movq: [{ mod: table_2.M.X64 },
        { o: 0x0F6E, ops: [table_2.mm, table_2.rm64], ext: [table_2.EXT.MMX] },
        { o: 0x0F7E, ops: [table_2.rm64, table_2.mm], ext: [table_2.EXT.MMX] },
        { o: 0x0F6E, pfx: [0x66], ops: [table_2.xmm, table_2.rm64], ext: [table_2.EXT.SSE2] },
        { o: 0x0F7E, pfx: [0x66], ops: [table_2.rm64, table_2.xmm], ext: [table_2.EXT.SSE2] },
        { o: 0x0F6F, ops: [table_2.mm, [table_2.mm, table_2.m64]], ext: [table_2.EXT.MMX] },
        { o: 0x0F7F, ops: [[table_2.mm, table_2.m64], table_2.mm], en: 'mr', ext: [table_2.EXT.MMX] },
        { o: 0xF30F7E, ops: [table_2.xmm, [table_2.xmm, table_2.m64]], ext: [table_2.EXT.SSE2] },
        { o: 0x660FD6, ops: [[table_2.xmm, table_2.m64], table_2.xmm], en: 'mr', ext: [table_2.EXT.SSE2] },
    ],
    vmovq: [{ mod: table_2.M.X64, ext: [table_2.EXT.AVX] },
        { o: 0x6E, vex: '128.66.0F.W1', ops: [table_2.xmm, table_2.rm64] },
        { o: 0x7E, vex: '128.66.0F.W1', ops: [table_2.rm64, table_2.xmm], en: 'mr' },
        { o: 0x7E, vex: '128.F3.0F.WIG', ops: [table_2.xmm, table_2.xmm] },
        { o: 0x7E, vex: '128.F3.0F.WIG', ops: [table_2.xmm, table_2.m64], s: table_1.S.Q },
        { o: 0xD6, vex: '128.66.0F.WIG', ops: [[table_2.xmm, table_2.m64], table_2.xmm], en: 'mr' },
    ],
    movddup: [{ o: 0xF20F12, ops: [table_2.xmm, [table_2.xmm, table_2.m]], ext: [table_2.EXT.SSE3] }],
    vmovddup: [{ o: 0x12, ext: [table_2.EXT.AVX] },
        { vex: '128.F2.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { vex: '256.F2.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
    ],
    movdqa: [{ pfx: [0x66, 0x0F], ext: [table_2.EXT.SSE2] },
        { o: 0x6F, ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { o: 0x7F, ops: [[table_2.xmm, table_2.m], table_2.xmm], en: 'mr' },
    ],
    vmovdqa: [{ ext: [table_2.EXT.AVX] },
        { o: 0x6F, vex: '128.66.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { o: 0x7F, vex: '128.66.0F.WIG', ops: [[table_2.xmm, table_2.m], table_2.xmm], en: 'mr' },
        { o: 0x6F, vex: '256.66.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
        { o: 0x7F, vex: '256.66.0F.WIG', ops: [[table_2.ymm, table_2.m], table_2.ymm], en: 'mr' },
    ],
    movdqu: [{ pfx: [0xF3, 0x0F], ext: [table_2.EXT.SSE2] },
        { o: 0x6F, ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { o: 0x7F, ops: [[table_2.xmm, table_2.m], table_2.xmm], en: 'mr' },
    ],
    vmovdqu: [{ ext: [table_2.EXT.AVX] },
        { o: 0x6F, vex: '128.F3.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m]] },
        { o: 0x7F, vex: '128.F3.0F.WIG', ops: [[table_2.xmm, table_2.m], table_2.xmm], en: 'mr' },
        { o: 0x6F, vex: '256.F3.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m]] },
        { o: 0x7F, vex: '256.F3.0F.WIG', ops: [[table_2.ymm, table_2.m], table_2.ymm], en: 'mr' },
    ],
    movdq2q: [{ o: 0xF20FD6, ops: [table_2.mm, table_2.xmm] }],
    movhlps: [{ o: 0x0F12, ops: [table_2.xmm, table_2.xmm], ext: [table_2.EXT.SSE] }],
    vmovhlps: [{ o: 0x12, vex: 'NDS.128.0F.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, table_2.xmm], ext: [table_2.EXT.AVX] }],
    movhpd: [{ pfx: [0x66, 0x0F], ext: [table_2.EXT.SSE2] },
        { o: 0x16, ops: [table_2.xmm, table_2.m64], dbit: true },
        { o: 0x17, ops: [table_2.m64, table_2.xmm], dbit: true, en: 'mr' },
    ],
    vmovhpd: [{ ext: [table_2.EXT.AVX] },
        { o: 0x16, vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, table_2.m64], en: 'rvm' },
        { o: 0x17, vex: '128.66.0F.WIG', ops: [table_2.m64, table_2.xmm], en: 'mr' },
    ],
    movhps: [{ pfx: [0x0F], ext: [table_2.EXT.SSE] },
        { o: 0x16, ops: [table_2.xmm, table_2.m64], dbit: true },
        { o: 0x17, ops: [table_2.m64, table_2.xmm], dbit: true, en: 'mr' },
    ],
    vmovhps: [{ ext: [table_2.EXT.AVX] },
        { o: 0x16, vex: 'NDS.128.0F.WIG', ops: [table_2.xmm, table_2.xmm, table_2.m64], en: 'rvm' },
        { o: 0x17, vex: '128.0F.WIG', ops: [table_2.m64, table_2.xmm], en: 'mr' },
    ],
    movlhps: [{ o: 0x0F16, ops: [table_2.xmm, table_2.xmm], ext: [table_2.EXT.SSE] }],
    vmovlhps: [{ o: 0x16, vex: 'NDS.128.0F.WIG', en: 'rvm', ops: [table_2.xmm, table_2.xmm, table_2.xmm], ext: [table_2.EXT.AVX] }],
    movlpd: [{ pfx: [0x66, 0x0F], ext: [table_2.EXT.SSE2] },
        { o: 0x12, ops: [table_2.xmm, table_2.m64], dbit: true },
        { o: 0x13, ops: [table_2.m64, table_2.xmm], dbit: true, en: 'mr' },
    ],
    vmovlpd: [{ ext: [table_2.EXT.AVX] },
        { o: 0x12, vex: 'NDS.128.66.0F.WIG', ops: [table_2.xmm, table_2.xmm, table_2.m64], en: 'rvm' },
        { o: 0x13, vex: '128.66.0F.WIG', ops: [table_2.m64, table_2.xmm], en: 'mr' },
    ],
    movlps: [{ pfx: [0x0F], ext: [table_2.EXT.SSE] },
        { o: 0x12, ops: [table_2.xmm, table_2.m64], dbit: true },
        { o: 0x13, ops: [table_2.m64, table_2.xmm], dbit: true, en: 'mr' },
    ],
    vmovlps: [{ ext: [table_2.EXT.AVX] },
        { o: 0x12, vex: 'NDS.128.0F.WIG', ops: [table_2.xmm, table_2.xmm, table_2.m64], en: 'rvm' },
        { o: 0x13, vex: '128.0F.WIG', ops: [table_2.m64, table_2.xmm], en: 'mr' },
    ],
    movmskpd: [{ o: 0x660F50, ops: [table_2.r, table_2.xmm], ext: [table_2.EXT.SSE2] }],
    vmovmskpd: [{ o: 0x50, ext: [table_2.EXT.AVX] },
        { vex: '128.66.0F.WIG', ops: [table_2.r, table_2.xmm] },
        { vex: '256.66.0F.WIG', ops: [table_2.r, table_2.ymm] },
    ],
    movmskps: [{ o: 0x0F50, ops: [table_2.r, table_2.xmm], ext: [table_2.EXT.SSE] }],
    vmovmskps: [{ o: 0x50, ext: [table_2.EXT.AVX] },
        { vex: '128.0F.WIG', ops: [table_2.r, table_2.xmm] },
        { vex: '256.0F.WIG', ops: [table_2.r, table_2.ymm] },
    ],
    movntdqa: [{ o: 0x382A, pfx: [0x66, 0x0F], ops: [table_2.xmm, table_2.m128], ext: [table_2.EXT.SSE4_1] }],
    vmovntdqa: [{ o: 0x2A },
        { vex: '128.66.0F38.WIG', ops: [table_2.xmm, table_2.m128], ext: [table_2.EXT.AVX] },
        { vex: '256.66.0F38.WIG', ops: [table_2.ymm, table_2.m256], ext: [table_2.EXT.AVX2] },
    ],
    movntdq: [{ o: 0xE7, pfx: [0x66, 0x0F], en: 'mr', ops: [table_2.m128, table_2.xmm], ext: [table_2.EXT.SSE2] }],
    vmovntdq: [{ o: 0xE7, ext: [table_2.EXT.AVX] },
        { vex: '128.66.0F.WIG', en: 'mr', ops: [table_2.m128, table_2.xmm] },
        { vex: '256.66.0F.WIG', en: 'mr', ops: [table_2.m256, table_2.ymm] },
    ],
    movnti: [{ o: 0x0FC3, en: 'mr' },
        { ops: [table_2.m32, table_2.r32] },
        { ops: [table_2.m64, table_2.r64] },
    ],
    movntpd: [{ o: 0x2B, pfx: [0x66, 0x0F], en: 'mr', ops: [table_2.m128, table_2.xmm], ext: [table_2.EXT.SSE2] }],
    vmovntpd: [{ o: 0x2B, ext: [table_2.EXT.AVX] },
        { vex: '128.66.0F.WIG', en: 'mr', ops: [table_2.m128, table_2.xmm] },
        { vex: '256.66.0F.WIG', en: 'mr', ops: [table_2.m256, table_2.ymm] },
    ],
    movntps: [{ o: 0x2B, pfx: [0x0F], en: 'mr', ops: [table_2.m128, table_2.xmm], ext: [table_2.EXT.SSE] }],
    vmovntps: [{ o: 0x2B, en: 'mr', ext: [table_2.EXT.AVX] },
        { vex: '128.0F.WIG', ops: [table_2.m128, table_2.xmm] },
        { vex: '256.0F.WIG', ops: [table_2.m256, table_2.ymm] },
    ],
    movntq: [{ o: 0x0FE7, ops: [table_2.m64, table_2.mm], en: 'mr' }],
    movq2dq: [{ o: 0xF30FD6, ops: [table_2.xmm, table_2.mm] }],
    movsd: [{ pfx: [0xF2, 0x0F], ext: [table_2.EXT.SSE2] },
        { o: 0x10, ops: [table_2.xmm, [table_2.xmm, table_2.m64]], dbit: true },
        { o: 0x11, ops: [[table_2.xmm, table_2.m64], table_2.xmm], dbit: true, en: 'mr' },
    ],
    vmovsd: [{ ext: [table_2.EXT.AVX] },
        { o: 0x10, vex: 'NDS.LIG.F2.0F.WIG', ops: [table_2.xmm, table_2.xmm, table_2.xmm], en: 'rvm' },
        { o: 0x10, vex: 'LIG.F2.0F.WIG', ops: [table_2.xmm, table_2.m64], en: 'rm' },
        { o: 0x11, vex: 'NDS.LIG.F2.0F.WIG', ops: [table_2.xmm, table_2.xmm, table_2.xmm], en: 'mvr' },
        { o: 0x11, vex: 'LIG.F2.0F.WIG', ops: [table_2.m64, table_2.xmm], en: 'mr' },
    ],
    movshdup: [{ o: 0xF30F16, ops: [table_2.xmm, [table_2.xmm, table_2.m128]], ext: [table_2.EXT.SSE3] }],
    vmovshdup: [{ o: 0x16, ext: [table_2.EXT.AVX] },
        { vex: '128.F3.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m128]] },
        { vex: '256.F3.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m256]] },
    ],
    movsldup: [{ o: 0xF30F12, ops: [table_2.xmm, [table_2.xmm, table_2.m128]], ext: [table_2.EXT.SSE3] }],
    vmovsldup: [{ o: 0x12, ext: [table_2.EXT.AVX] },
        { vex: '128.F3.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m128]] },
        { vex: '256.F3.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m256]] },
    ],
    movss: [{ ext: [table_2.EXT.SSE] },
        { o: 0xF30F10, ops: [table_2.xmm, [table_2.xmm, table_2.m32]] },
        { o: 0xF30F11, ops: [[table_2.xmm, table_2.m32], table_2.xmm], en: 'mr' },
    ],
    vmovss: [{ ext: [table_2.EXT.AVX] },
        { o: 0x10, vex: 'NDS.LIG.F3.0F.WIG', ops: [table_2.xmm, table_2.xmm, table_2.xmm], en: 'rvm' },
        { o: 0x10, vex: 'LIG.F3.0F.WIG', ops: [table_2.xmm, table_2.m32] },
        { o: 0x11, vex: 'NDS.LIG.F3.0F.WIG', ops: [table_2.xmm, table_2.xmm, table_2.xmm], en: 'mvr' },
        { o: 0x11, vex: 'LIG.F3.0F.WIG', ops: [table_2.m32, table_2.xmm], en: 'mr' },
    ],
    movupd: [{ ext: [table_2.EXT.SSE2] },
        { o: 0x660F10, ops: [table_2.xmm, [table_2.xmm, table_2.m128]] },
        { o: 0x660F11, ops: [[table_2.xmm, table_2.m128], table_2.xmm], en: 'mr' },
    ],
    vmovupd: [{ ext: [table_2.EXT.AVX] },
        { o: 0x10, vex: '128.66.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m128]] },
        { o: 0x10, vex: '256.66.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m256]] },
        { o: 0x11, vex: '128.66.0F.WIG', ops: [table_2.xmm, [table_2.xmm, table_2.m128]], en: 'mr' },
        { o: 0x11, vex: '256.66.0F.WIG', ops: [table_2.ymm, [table_2.ymm, table_2.m256]], en: 'mr' },
    ],
    mov: [{},
        { o: 0x88, ops: [table_2.rm8, table_2.r8], en: 'mr', dbit: true },
        { o: 0x8A, ops: [table_2.r8, table_2.rm8], dbit: true },
        { o: 0x89, ops: [table_2.rm16, table_2.r16], en: 'mr', dbit: true },
        { o: 0x8B, ops: [table_2.r16, table_2.rm16], dbit: true },
        { o: 0x89, ops: [table_2.rm32, table_2.r32], en: 'mr', dbit: true },
        { o: 0x8B, ops: [table_2.r32, table_2.rm32], dbit: true },
        { o: 0x89, ops: [table_2.rm64, table_2.r64], en: 'mr', dbit: true },
        { o: 0x8B, ops: [table_2.r64, table_2.rm64], dbit: true },
        { o: 0x8C, ops: [table_2.rm16, table_2.sreg], s: table_1.S.W },
        { o: 0x8E, ops: [table_2.sreg, table_2.rm16], s: table_1.S.W },
        { o: 0x8C, ops: [table_2.rm64, table_2.sreg], s: table_1.S.W },
        { o: 0x8E, ops: [table_2.sreg, table_2.rm64], s: table_1.S.W },
        { o: 0xB0, r: true, ops: [table_2.r8, table_1.imm8] },
        { o: 0xB8, r: true, ops: [table_2.r16, table_1.imm16] },
        { o: 0xB8, r: true, ops: [table_2.r32, table_1.imm32] },
        { o: 0xB8, r: true, ops: [table_2.r64, table_1.imm64] },
        { o: 0xC6, or: 0, ops: [table_2.rm8, table_1.imm8] },
        { o: 0xC7, or: 0, ops: [table_2.rm16, table_1.imm16] },
        { o: 0xC7, or: 0, ops: [table_2.rm32, table_1.imm32] },
        { o: 0xC7, or: 0, ops: [table_2.rm64, table_1.imm32] },
        { o: 0x0F20, ops: [table_2.r32, exports.cr0_7], dbit: true, s: table_1.S.D, mod: table_2.M.COMP | table_2.M.LEG },
        { o: 0x0F20, ops: [table_2.r64, exports.cr0_7], dbit: true, s: table_1.S.Q, mod: table_2.M.X64 },
        { o: 0x0F20, or: 0, ops: [table_2.r64, o.cr(8)], s: table_1.S.Q, mod: table_2.M.X64 },
        { o: 0x0F22, ops: [exports.cr0_7, table_2.r32], dbit: true, s: table_1.S.D, mod: table_2.M.COMP | table_2.M.LEG },
        { o: 0x0F22, ops: [exports.cr0_7, table_2.r64], dbit: true, s: table_1.S.Q, mod: table_2.M.X64 },
        { o: 0x0F22, or: 0, ops: [o.cr(8), table_2.r64], s: table_1.S.Q, mod: table_2.M.X64 },
        { o: 0x0F21, ops: [table_2.r32, exports.dr0_7], dbit: true, s: table_1.S.D, mod: table_2.M.COMP | table_2.M.LEG },
        { o: 0x0F23, ops: [exports.dr0_7, table_2.r32], dbit: true, s: table_1.S.D, mod: table_2.M.COMP | table_2.M.LEG },
        { o: 0x0F21, ops: [table_2.r64, exports.dr0_7], dbit: true, s: table_1.S.Q, mod: table_2.M.X64 },
        { o: 0x0F23, ops: [exports.dr0_7, table_2.r64], dbit: true, s: table_1.S.Q, mod: table_2.M.X64 },
    ],
    movabs: [{},
        { o: 0xA0, ops: [o.al, table_1.imm8] },
        { o: 0xA1, ops: [o.ax, table_1.imm16] },
        { o: 0xA1, ops: [o.eax, table_1.imm32] },
        { o: 0xA1, ops: [o.rax, table_1.imm64] },
        { o: 0xA2, ops: [table_1.imm8, o.al] },
        { o: 0xA3, ops: [table_1.imm16, o.ax] },
        { o: 0xA3, ops: [table_1.imm32, o.eax] },
        { o: 0xA3, ops: [table_1.imm64, o.rax] },
    ],
    cmove: tpl_cmovc(0x0F44),
    cmovz: ['cmove'],
    cmovne: tpl_cmovc(0x0F45),
    cmovnz: ['cmovne'],
    cmova: tpl_cmovc(0x0F47),
    cmovnbe: ['cmova'],
    cmovae: tpl_cmovc(0x0F43),
    cmovnb: ['cmovae'],
    cmovb: tpl_cmovc(0x0F42),
    cmovnae: ['cmovb'],
    cmovbe: tpl_cmovc(0x0F46),
    cmovna: ['cmovbe'],
    cmovg: tpl_cmovc(0x0F4F),
    cmovnle: ['cmovg'],
    cmovge: tpl_cmovc(0x0F4D),
    cmovnl: ['cmovge'],
    cmovl: tpl_cmovc(0x0F4C),
    cmovnge: ['cmovl'],
    cmovle: tpl_cmovc(0x0F4E),
    cmovng: ['cmovle'],
    cmovc: tpl_cmovc(),
    cmovnc: tpl_cmovc(0x0F43),
    cmovo: tpl_cmovc(0x0F40),
    cmovno: tpl_cmovc(0x0F41),
    cmovs: tpl_cmovc(0x0F48),
    cmovns: tpl_cmovc(0x0F4B),
    cmovp: tpl_cmovc(0x0F4A),
    cmovpe: ['cmovp'],
    cmovnp: tpl_cmovc(0x0F4B),
    cmovpo: ['cmovnp'],
    xchg: [{},
        { o: 0x90, r: true, ops: [o.ax, table_2.r16] },
        { o: 0x90, r: true, ops: [table_2.r16, o.ax] },
        { o: 0x90, r: true, ops: [o.eax, table_2.r32] },
        { o: 0x90, r: true, ops: [o.rax, table_2.r64] },
        { o: 0x90, r: true, ops: [table_2.r32, o.eax] },
        { o: 0x90, r: true, ops: [table_2.r64, o.rax] },
        { o: 0x86, ops: [table_2.rm8, table_2.rm8] },
        { o: 0x87, ops: [table_2.rm16, table_2.rm16] },
        { o: 0x87, ops: [table_2.rm32, table_2.rm32] },
        { o: 0x87, ops: [table_2.rm64, table_2.rm64] },
    ],
    bswap: [{ o: 0x0FC8, r: true },
        { ops: [table_2.r32] },
        { ops: [table_2.r64] },
    ],
    xadd: tpl_xadd(0x0FC0),
    cmpxchg: tpl_xadd(0x0FB0),
    cmpxchg8b: [{ o: 0x0FC7, or: 1, ops: [table_2.m], s: table_1.S.Q }],
    cmpxchg16b: [{ o: 0x0FC7, or: 1, ops: [table_2.m], s: table_1.S.O }],
    push: [{ ds: table_1.S.Q },
        { o: 0xFF, or: 6, ops: [table_2.rm16] },
        { o: 0xFF, or: 6, ops: [table_2.rm64] },
        { o: 0x50, r: true, ops: [table_2.r16] },
        { o: 0x50, r: true, ops: [table_2.r64] },
        { o: 0x6A, ops: [table_1.imm8] },
        { o: 0x68, ops: [table_1.imm16] },
        { o: 0x68, ops: [table_1.imm32] },
        { o: 0x0FA0, ops: [o.fs] },
        { o: 0x0FA8, ops: [o.gs] },
    ],
    pop: [{ ds: table_1.S.Q },
        { o: 0x8F, or: 0, ops: [table_2.rm16] },
        { o: 0x8F, or: 0, ops: [table_2.rm64] },
        { o: 0x58, r: true, ops: [table_2.rm16] },
        { o: 0x58, r: true, ops: [table_2.rm64] },
        { o: 0x0FA1, ops: [o.fs], s: table_1.S.W },
        { o: 0x0FA1, ops: [o.fs], s: table_1.S.Q },
        { o: 0x0FA9, ops: [o.gs], s: table_1.S.W },
        { o: 0x0FA9, ops: [o.gs], s: table_1.S.W },
    ],
    cwd: [{ o: 0x99, s: table_1.S.W }],
    cdq: [{ o: 0x99, s: table_1.S.D }],
    cqo: [{ o: 0x99, s: table_1.S.Q }],
    cbw: [{ o: 0x98, s: table_1.S.W }],
    cwde: [{ o: 0x98, s: table_1.S.D }],
    cdqe: [{ o: 0x98, s: table_1.S.Q }],
    movsx: [{},
        { o: 0x0FBE, ops: [table_2.r16, table_2.rm8], s: table_1.S.W },
        { o: 0x0FBE, ops: [table_2.r32, table_2.rm8], s: table_1.S.D },
        { o: 0x0FBE, ops: [table_2.r64, table_2.rm8], s: table_1.S.Q },
        { o: 0x0FBF, ops: [table_2.r32, table_2.rm16], s: table_1.S.D },
        { o: 0x0FBF, ops: [table_2.r64, table_2.rm16], s: table_1.S.Q },
    ],
    movsxd: [{ o: 0x63, ops: [table_2.r64, table_2.rm32], s: table_1.S.Q }],
    movzx: [{},
        { o: 0x0FB6, ops: [table_2.r16, table_2.rm8], s: table_1.S.W },
        { o: 0x0FB6, ops: [table_2.r32, table_2.rm8], s: table_1.S.D },
        { o: 0x0FB6, ops: [table_2.r64, table_2.rm8], s: table_1.S.Q },
        { o: 0x0FB7, ops: [table_2.r32, table_2.rm16], s: table_1.S.D },
        { o: 0x0FB7, ops: [table_2.r64, table_2.rm16], s: table_1.S.Q },
    ],
    adcx: [{ o: 0x0F38F6, pfx: [0x66], ext: [table_2.EXT.ADX] },
        { ops: [table_2.r32, table_2.rm32] },
        { ops: [table_2.r64, table_2.rm64], mod: table_2.M.X64 },
    ],
    adox: [{ o: 0x0F38F6, pfx: [0xF3], ext: [table_2.EXT.ADX] },
        { ops: [table_2.r32, table_2.rm32] },
        { ops: [table_2.r64, table_2.rm64], mod: table_2.M.X64 },
    ],
    add: tpl_and(0x04, 0x80, 0, 0x00),
    adc: tpl_and(0x14, 0x80, 2, 0x10),
    sub: tpl_and(0x2C, 0x80, 5, 0x28),
    sbb: tpl_and(0x1C, 0x80, 3, 0x18),
    imul: [{},
        { o: 0xF6, or: 5, ops: [table_2.rm8] },
        { o: 0xF7, or: 5, ops: [table_2.rm16] },
        { o: 0xF7, or: 5, ops: [table_2.rm32] },
        { o: 0xF7, or: 5, ops: [table_2.rm64] },
        { o: 0x0FAF, ops: [table_2.r16, table_2.rm16] },
        { o: 0x0FAF, ops: [table_2.r32, table_2.rm32] },
        { o: 0x0FAF, ops: [table_2.r64, table_2.rm64] },
        { o: 0x6B, ops: [table_2.r16, table_2.rm16, table_1.imm8] },
        { o: 0x6B, ops: [table_2.r32, table_2.rm32, table_1.imm8] },
        { o: 0x6B, ops: [table_2.r64, table_2.rm64, table_1.imm8] },
        { o: 0x69, ops: [table_2.r16, table_2.rm16, table_1.imm16] },
        { o: 0x69, ops: [table_2.r32, table_2.rm32, table_1.imm32] },
        { o: 0x69, ops: [table_2.r64, table_2.rm64, table_1.imm32] },
    ],
    mul: tpl_not(0xF6, 4, false),
    idiv: tpl_not(0xF6, 7, false),
    div: tpl_not(0xF6, 6, false),
    inc: _inc,
    dec: _dec,
    neg: tpl_not(0xF6, 3),
    cmp: tpl_and(0x3C, 0x80, 7, 0x38, false),
    and: tpl_and(),
    or: tpl_and(0x0C, 0x80, 1, 0x08),
    xor: tpl_and(0x34, 0x80, 6, 0x30),
    not: tpl_not(),
    sar: tpl_sar(),
    shr: tpl_sar(5),
    shl: tpl_sar(4, 0xD0, 0xC0),
    sal: ['shl'],
    shrd: tpl_shrd(),
    shld: tpl_shrd(0x0FA4),
    ror: tpl_sar(1),
    rol: tpl_sar(0),
    rcr: tpl_sar(3),
    rcl: tpl_sar(2),
    bt: tpl_bt(),
    bts: tpl_bt(0x0FAB, 4),
    btr: tpl_bt(0x0FB3, 6),
    btc: tpl_bt(0x0FBB, 7),
    bsf: tpl_bsf(),
    bsr: tpl_bsf(0x0FBD),
    sete: [{ o: 0x0F94, ops: [table_2.rm8] }],
    setz: ['sete'],
    setne: [{ o: 0x0F95, ops: [table_2.rm8] }],
    setnz: ['setne'],
    seta: [{ o: 0x0F97, ops: [table_2.rm8] }],
    setnbe: ['seta'],
    setae: [{ o: 0x0F93, ops: [table_2.rm8] }],
    setnb: ['setae'],
    setnc: ['setae'],
    setb: [{ o: 0x0F92, ops: [table_2.rm8] }],
    setnae: ['setb'],
    setc: ['setb'],
    setbe: [{ o: 0x0F96, ops: [table_2.rm8] }],
    setna: ['setbe'],
    setg: [{ o: 0x0F9F, ops: [table_2.rm8] }],
    setnle: ['setg'],
    setge: [{ o: 0x0F9D, ops: [table_2.rm8] }],
    setnl: ['setge'],
    setl: [{ o: 0x0F9C, ops: [table_2.rm8] }],
    setnge: ['setl'],
    setle: [{ o: 0x0F9E, ops: [table_2.rm8] }],
    setng: ['setle'],
    sets: [{ o: 0x0F98, ops: [table_2.rm8] }],
    setns: [{ o: 0x0F99, ops: [table_2.rm8] }],
    seto: [{ o: 0x0F90, ops: [table_2.rm8] }],
    setno: [{ o: 0x0F91, ops: [table_2.rm8] }],
    setp: [{ o: 0x0F9A, ops: [table_2.rm8] }],
    setpe: ['setp'],
    setnp: [{ o: 0x0F9B, ops: [table_2.rm8] }],
    setpo: ['setnp'],
    test: [{},
        { o: 0xA8, ops: [o.al, table_1.imm8] },
        { o: 0xA9, ops: [o.ax, table_1.imm16] },
        { o: 0xA9, ops: [o.eax, table_1.imm32] },
        { o: 0xA9, ops: [o.rax, table_1.imm32] },
        { o: 0xF6, or: 0, ops: [table_2.rm8, table_1.imm8] },
        { o: 0xF7, or: 0, ops: [table_2.rm16, table_1.imm16] },
        { o: 0xF7, or: 0, ops: [table_2.rm32, table_1.imm32] },
        { o: 0xF7, or: 0, ops: [table_2.rm64, table_1.imm32] },
        { o: 0x84, ops: [table_2.rm8, table_2.r8] },
        { o: 0x85, ops: [table_2.rm16, table_2.r16] },
        { o: 0x85, ops: [table_2.rm32, table_2.r32] },
        { o: 0x85, ops: [table_2.rm64, table_2.r64] },
    ],
    crc32: [{ pfx: [0xF2] },
        { o: 0x0F38F0, ops: [table_2.r32, table_2.rm8], s: table_1.S.D },
        { o: 0x0F38F1, ops: [table_2.r32, table_2.rm16], s: table_1.S.D },
        { o: 0x0F38F1, ops: [table_2.r32, table_2.rm32], s: table_1.S.D },
        { o: 0x0F38F0, ops: [table_2.r64, table_2.rm8], s: table_1.S.Q },
        { o: 0x0F38F1, ops: [table_2.r64, table_2.rm64] },
    ],
    popcnt: [{ pfx: [0xF3] },
        { o: 0x0FB8, ops: [table_2.r16, table_2.rm16], s: table_1.S.W },
        { o: 0x0FB8, ops: [table_2.r32, table_2.rm32], s: table_1.S.D },
        { o: 0x0FB8, ops: [table_2.r64, table_2.rm64], s: table_1.S.Q },
    ],
    jmp: [{ ds: table_1.S.Q },
        { o: 0xEB, ops: [table_1.rel8] },
        { o: 0xE9, ops: [table_1.rel32] },
        { o: 0xFF, or: 4, ops: [table_2.rm64] },
    ],
    ljmp: [{ ds: table_1.S.Q },
        { o: 0xFF, or: 5, ops: [table_2.m], s: table_1.S.Q },
    ],
    jecxz: [{ o: 0xE3, ops: [table_1.rel8], pfx: [0x67] }],
    jrcxz: [{ o: 0xE3, ops: [table_1.rel8] }],
    ja: tpl_ja(),
    jae: tpl_ja(0x73, 0x0F83),
    jb: tpl_ja(0x72, 0x0F82),
    jbe: tpl_ja(0x76, 0x0F86),
    jc: tpl_ja(0x72, 0x0F82),
    je: tpl_ja(0x74, 0x0F84),
    jg: tpl_ja(0x7F, 0x0F8F),
    jge: tpl_ja(0x7D, 0x0F8D),
    jl: tpl_ja(0x7C, 0x0F8C),
    jle: tpl_ja(0x7E, 0x0F8E),
    jna: tpl_ja(0x76, 0x0F86),
    jnae: tpl_ja(0x72, 0x0F82),
    jnb: tpl_ja(0x73, 0x0F83),
    jnbe: tpl_ja(0x77, 0x0F87),
    jnc: tpl_ja(0x73, 0x0F83),
    jne: tpl_ja(0x75, 0x0F85),
    jng: tpl_ja(0x7E, 0x0F8E),
    jnge: tpl_ja(0x7C, 0x0F8C),
    jnl: tpl_ja(0x7D, 0x0F8D),
    jnle: tpl_ja(0x7F, 0x0F8F),
    jno: tpl_ja(0x71, 0x0F81),
    jnp: tpl_ja(0x7B, 0x0F8B),
    jns: tpl_ja(0x79, 0x0F89),
    jnz: tpl_ja(0x75, 0x0F85),
    jo: tpl_ja(0x70, 0x0F80),
    jp: tpl_ja(0x7A, 0x0F8A),
    jpe: tpl_ja(0x7A, 0x0F8A),
    jpo: tpl_ja(0x7B, 0x0F8B),
    js: tpl_ja(0x78, 0x0F88),
    jz: tpl_ja(0x74, 0x0F84),
    loop: [{ o: 0xE2, ops: [table_1.rel8] }],
    loope: [{ o: 0xE1, ops: [table_1.rel8] }],
    loopz: ['loope'],
    loopne: [{ o: 0xE0, ops: [table_1.rel8] }],
    loopnz: ['loopne'],
    call: [{ ds: table_1.S.Q },
        { o: 0xE8, ops: [table_1.rel16], mod: table_2.M.OLD },
        { o: 0xE8, ops: [table_1.rel32] },
        { o: 0xFF, or: 2, ops: [table_2.rm16], mod: table_2.M.OLD },
        { o: 0xFF, or: 2, ops: [table_2.rm32], mod: table_2.M.OLD },
        { o: 0xFF, or: 2, ops: [table_2.rm64] },
    ],
    lcall: [{ ds: table_1.S.Q },
        { o: 0xFF, or: 3, ops: [table_2.m], s: table_1.S.D },
    ],
    ret: [{ ds: table_1.S.Q },
        { o: 0xC3 },
        { o: 0xC2, ops: [table_1.imm16] }
    ],
    lret: [{ ds: table_1.S.Q },
        { o: 0xCB },
        { o: 0xCA, ops: [table_1.imm16] }
    ],
    iret: [{ o: 0xCF }],
    iretd: [{ o: 0xCF }],
    iretq: [{ o: 0xCF, rex: [1, 0, 0, 0] }],
    movs: tpl_movs(),
    cmps: tpl_movs(0xA6),
    scas: tpl_movs(0xAE),
    lods: tpl_movs(0xAC),
    lodsb: [{ o: 0xAC, s: table_1.S.B }],
    lodsw: [{ o: 0xAD, s: table_1.S.W }],
    lodsd: [{ o: 0xAD, s: table_1.S.D }],
    lodsq: [{ o: 0xAD, s: table_1.S.Q }],
    stos: tpl_movs(0xAA),
    'in': [{ mr: false },
        { o: 0xE4, ops: [o.al, table_1.imm8] },
        { o: 0xE5, ops: [o.ax, table_1.imm8] },
        { o: 0xE5, ops: [o.eax, table_1.imm8] },
        { o: 0xEC, ops: [o.al, o.dx], s: table_1.S.B },
        { o: 0xED, ops: [o.ax, o.dx], s: table_1.S.W },
        { o: 0xED, ops: [o.eax, o.dx], s: table_1.S.D },
    ],
    out: [{ mr: false },
        { o: 0xE6, ops: [table_1.imm8, o.al] },
        { o: 0xE7, ops: [table_1.imm8, o.ax] },
        { o: 0xE7, ops: [table_1.imm8, o.eax] },
        { o: 0xEE, ops: [o.dx, o.al], s: table_1.S.B },
        { o: 0xEF, ops: [o.dx, o.ax], s: table_1.S.W },
        { o: 0xEF, ops: [o.dx, o.eax], s: table_1.S.D },
    ],
    ins: [{ o: 0x6D },
        { o: 0x6C, s: table_1.S.B },
        { s: table_1.S.W },
        { s: table_1.S.D },
    ],
    insb: [{ o: 0x6C }],
    insw: [{ o: 0x6D }],
    insd: [{ o: 0x6D }],
    outs: [{ o: 0x6F },
        { o: 0x6E, s: table_1.S.B },
        { s: table_1.S.W },
        { s: table_1.S.D },
    ],
    enter: [{ o: 0xC8, ops: [table_1.imm16, table_1.imm8] },
    ],
    leave: [{ o: 0xC9 },
        { s: table_1.S.W },
        { s: table_1.S.D, mod: table_2.M.COMP | table_2.M.LEG },
        { s: table_1.S.Q, mod: table_2.M.X64 },
    ],
    stc: [{ o: 0xF9 }],
    clc: [{ o: 0xF8 }],
    cmc: [{ o: 0xF5 }],
    cld: [{ o: 0xFC }],
    std: [{ o: 0xFD }],
    pushf: [{ o: 0x9C }],
    popf: [{ o: 0x9D }],
    sti: [{ o: 0xFB }],
    cli: [{ o: 0xFA }],
    clac: [{ o: 0x0F01CA }],
    lds: [{ o: 0xC5, mod: table_2.M.COMP | table_2.M.LEG },
        { ops: [table_2.r16, table_2.m] },
        { ops: [table_2.r32, table_2.m] },
    ],
    les: [{ o: 0xC4, mod: table_2.M.COMP | table_2.M.LEG },
        { ops: [table_2.r16, table_2.m] },
        { ops: [table_2.r32, table_2.m] },
    ],
    lfs: tpl_lss(0x0FB4),
    lgs: tpl_lss(0x0FB5),
    lss: tpl_lss(),
    lea: [{ o: 0x8D },
        { ops: [table_2.r16, table_2.m] },
        { ops: [table_2.r32, table_2.m] },
        { ops: [table_2.r64, table_2.m] },
    ],
    nop: [{},
        { o: 0x90 },
        { o: 0x0F1F, or: 0, ops: [table_2.rm16] },
        { o: 0x0F1F, or: 0, ops: [table_2.rm32] },
    ],
    ud2: [{ o: 0x0F0B }],
    xlat: [{ o: 0xD7 }],
    cpuid: [{ o: 0x0FA2 }],
    movbe: [{},
        { o: 0x0F38F0, ops: [table_2.r16, table_2.m16], dbit: true },
        { o: 0x0F38F0, ops: [table_2.r32, table_2.m32], dbit: true },
        { o: 0x0F38F0, ops: [table_2.r64, table_2.m64], dbit: true },
        { o: 0x0F38F1, ops: [table_2.m16, table_2.r16], dbit: true },
        { o: 0x0F38F1, ops: [table_2.m32, table_2.r32], dbit: true },
        { o: 0x0F38F1, ops: [table_2.m64, table_2.r64], dbit: true },
    ],
    prefetchw: [{ o: 0x0F0D, or: 1, ops: [table_2.m] }],
    prefetchwt1: [{ o: 0x0F0D, or: 2, ops: [table_2.m] }],
    cflush: [{ o: 0x0FAE, or: 7, ops: [table_2.m] }],
    cflushopt: [{ o: 0x0FAE, or: 7, pfx: [0x66], ops: [table_2.m] }],
    xsave: [{ o: 0x0FAE, or: 4, ops: [table_2.m] }],
    xsavec: [{ o: 0x0FC7, or: 4, ops: [table_2.m] }],
    xsaveopt: [{ o: 0x0FAE, or: 6, ops: [table_2.m] }],
    xrstor: [{ o: 0x0FAE, or: 5, ops: [table_2.m] }],
    xgetbv: [{ o: 0x0F01D0 }],
    rdrand: [{ o: 0x0FC7, or: 6 },
        { ops: [table_2.r16] },
        { ops: [table_2.r32] },
        { ops: [table_2.r64] },
    ],
    rdseed: [{ o: 0x0FC7, or: 7 },
        { ops: [table_2.r16] },
        { ops: [table_2.r32] },
        { ops: [table_2.r64] },
    ],
    syscall: [{ o: 0x0F05 }],
    sysret: [{ o: 0x0F07 }],
    sysenter: [{ o: 0x0F34 }],
    sysexit: [{ o: 0x0F35 }],
    vextractf128: [{ o: 0x19, vex: '256.66.0F3A.W0', ops: [[table_2.xmm, table_2.m], table_2.ymm, table_1.imm8], s: table_1.S.X }],
    vcvtph2ps: [{ o: 0x13, vex: '256.66.0F38.W0', ops: [table_2.ymm, [table_2.xmm, table_2.m]], s: 256 }],
    vfmadd132pd: [{ o: 0x98, vex: 'DDS.128.66.0F38.W1', en: 'rvm', ops: [table_2.xmm, table_2.xmm, [table_2.xmm, table_2.m]] }],
});
