"use strict";
var o = require('../x86/operand');
var code_1 = require('../x86/x64/code');
var code = code_1.Code.create();
var last = code.lbl('last');
code.add(o.al, 0x11);
code.adox(o.rax, o.rax);
code.insert(last);
code.mulw(o.rax.ref());
console.log(code.toString());
