// Generated by CoffeeScript 1.10.0
(function() {
  var Code, StaticBuffer, _, msg, rax, rdi, rdx, ref, rip, rsi;

  ref = require('../x86/operand'), rax = ref.rax, rdx = ref.rdx, rsi = ref.rsi, rdi = ref.rdi, rip = ref.rip;

  Code = require('../x86/x64/code').Code;

  StaticBuffer = require('../../static-buffer/buffer').StaticBuffer;

  _ = Code.create();

  msg = 'Hello World!\n';

  _.movq(rax, 1);

  _.movq(rdi, 1);

  _.lea(rsi, rip.disp(10));

  _.movq(rdx, msg.length);

  _.syscall();

  _.ret();

  _.db(msg);

  StaticBuffer.from(_.compile(), 'rwe').call();

}).call(this);
