import * as d from '../x86/def';
import * as t from '../x86/x64/table';
import * as o from '../x86/operand';
import {Code} from '../x86/x64/code';


var code = Code.create();
var start = code.getStartLabel();
var end = code.lbl('end');

code._('jmp', start);
code._('jmp', end);

code._('jecxz', start);
code._('jrcxz', start);

code._('ja', start);
code._('jae', start);
code._('jb', start);
code._('jbe', start);
code._('jc', start);
code._('je', start);
code._('jg', start);
code._('jge', start);
code._('jl', start);
code._('jle', start);
code._('jna', start);
code._('jnae', start);
code._('jnb', start);
code._('jnbe', start);
code._('jnc', start);
code._('jne', start);
code._('jng', start);
code._('jnge', start);
code._('jnl', start);
code._('jnle', start);
code._('jno', start);
code._('jnp', start);
code._('jns', start);
code._('jnz', start);
code._('jo', start);
code._('jp', start);
code._('jpe', start);
code._('jpo', start);
code._('js', start);
code._('jz', start);

code._('ja', end);
code._('jae', end);
code._('jb', end);
code._('jbe', end);
code._('jc', end);
code._('je', end);
code._('jg', end);
code._('jge', end);
code._('jl', end);
code._('jle', end);
code._('jna', end);
code._('jnae', end);
code._('jnb', end);
code._('jnbe', end);
code._('jnc', end);
code._('jne', end);
code._('jng', end);
code._('jnge', end);
code._('jnl', end);
code._('jnle', end);
code._('jno', end);
code._('jnp', end);
code._('jns', end);
code._('jnz', end);
code._('jo', end);
code._('jp', end);
code._('jpe', end);
code._('jpo', end);
code._('js', end);
code._('jz', end);

code.resb(200);

code._('ja', start);
code._('jae', start);
code._('jb', start);
code._('jbe', start);
code._('jc', start);
code._('je', start);
code._('jg', start);
code._('jge', start);
code._('jl', start);
code._('jle', start);
code._('jna', start);
code._('jnae', start);
code._('jnb', start);
code._('jnbe', start);
code._('jnc', start);
code._('jne', start);
code._('jng', start);
code._('jnge', start);
code._('jnl', start);
code._('jnle', start);
code._('jno', start);
code._('jnp', start);
code._('jns', start);
code._('jnz', start);
code._('jo', start);
code._('jp', start);
code._('jpe', start);
code._('jpo', start);
code._('js', start);
code._('jz', start);

code._('ja', end);
code._('jae', end);
code._('jb', end);
code._('jbe', end);
code._('jc', end);
code._('je', end);
code._('jg', end);
code._('jge', end);
code._('jl', end);
code._('jle', end);
code._('jna', end);
code._('jnae', end);
code._('jnb', end);
code._('jnbe', end);
code._('jnc', end);
code._('jne', end);
code._('jng', end);
code._('jnge', end);
code._('jnl', end);
code._('jnle', end);
code._('jno', end);
code._('jnp', end);
code._('jns', end);
code._('jnz', end);
code._('jo', end);
code._('jp', end);
code._('jpe', end);
code._('jpo', end);
code._('js', end);
code._('jz', end);

code._('jmp', start);
code._('jmp', end);

code._('insert', end);

console.log(code.toString() + '\n\n');
var bin = code.compile();
console.log(code.toString() + '\n\n');

