// Generated by CoffeeScript 1.10.0
(function() {
  var code, imm, operand;

  code = require('./code');

  operand = require('./operand');

  imm = new operand.Immediate([12332323, 123]);

  console.log(imm);

}).call(this);
